# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'unitWidget_ECP_rev5.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_unitWidget_ECP(object):
    def setupUi(self, unitWidget_ECP):
        unitWidget_ECP.setObjectName("unitWidget_ECP")
        unitWidget_ECP.resize(2010, 4095)
        self.gridLayout = QtWidgets.QGridLayout(unitWidget_ECP)
        self.gridLayout.setObjectName("gridLayout")
        self.ECP_frame_MainWindow = QtWidgets.QFrame(unitWidget_ECP)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ECP_frame_MainWindow.sizePolicy().hasHeightForWidth())
        self.ECP_frame_MainWindow.setSizePolicy(sizePolicy)
        self.ECP_frame_MainWindow.setStyleSheet("background-color: rgb(44, 49, 60);\n"
"/* LINE EDIT */\n"
"QLineEdit {\n"
"    background-color: rgb(27, 29, 35);\n"
"    border-radius: 5px;\n"
"    border: 2px solid rgb(27, 29, 35);\n"
"    padding-left: 10px;\n"
"}\n"
"QLineEdit:hover {\n"
"    border: 2px solid rgb(64, 71, 88);\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 2px solid rgb(91, 101, 124);\n"
"}\n"
"\n"
"/* SCROLL BARS */\n"
"QScrollBar:horizontal {\n"
"    border: none;\n"
"    background: rgb(52, 59, 72);\n"
"    height: 14px;\n"
"    margin: 0px 21px 0 21px;\n"
"    border-radius: 0px;\n"
"}\n"
"QScrollBar::handle:horizontal {\n"
"    background: rgb(85, 170, 255);\n"
"    min-width: 25px;\n"
"    border-radius: 7px\n"
"}\n"
"QScrollBar::add-line:horizontal {\n"
"    border: none;\n"
"    background: rgb(55, 63, 77);\n"
"    width: 20px;\n"
"    border-top-right-radius: 7px;\n"
"    border-bottom-right-radius: 7px;\n"
"    subcontrol-position: right;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::sub-line:horizontal {\n"
"    border: none;\n"
"    background: rgb(55, 63, 77);\n"
"    width: 20px;\n"
"    border-top-left-radius: 7px;\n"
"    border-bottom-left-radius: 7px;\n"
"    subcontrol-position: left;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::up-arrow:horizontal, QScrollBar::down-arrow:horizontal\n"
"{\n"
"     background: none;\n"
"}\n"
"QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal\n"
"{\n"
"     background: none;\n"
"}\n"
" QScrollBar:vertical {\n"
"    border: none;\n"
"    background: rgb(52, 59, 72);\n"
"    width: 14px;\n"
"    margin: 21px 0 21px 0;\n"
"    border-radius: 0px;\n"
" }\n"
" QScrollBar::handle:vertical {    \n"
"    background: rgb(85, 170, 255);\n"
"    min-height: 25px;\n"
"    border-radius: 7px\n"
" }\n"
" QScrollBar::add-line:vertical {\n"
"     border: none;\n"
"    background: rgb(55, 63, 77);\n"
"     height: 20px;\n"
"    border-bottom-left-radius: 7px;\n"
"    border-bottom-right-radius: 7px;\n"
"     subcontrol-position: bottom;\n"
"     subcontrol-origin: margin;\n"
" }\n"
" QScrollBar::sub-line:vertical {\n"
"    border: none;\n"
"    background: rgb(55, 63, 77);\n"
"     height: 20px;\n"
"    border-top-left-radius: 7px;\n"
"    border-top-right-radius: 7px;\n"
"     subcontrol-position: top;\n"
"     subcontrol-origin: margin;\n"
" }\n"
" QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical {\n"
"     background: none;\n"
" }\n"
"\n"
" QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"     background: none;\n"
" }\n"
"\n"
"/* CHECKBOX */\n"
"QCheckBox::indicator {\n"
"    border: 3px solid rgb(52, 59, 72);\n"
"    width: 15px;\n"
"    height: 15px;\n"
"    border-radius: 10px;\n"
"    background: rgb(44, 49, 60);\n"
"}\n"
"QCheckBox::indicator:hover {\n"
"    border: 3px solid rgb(58, 66, 81);\n"
"}\n"
"QCheckBox::indicator:checked {\n"
"    background: 3px solid rgb(52, 59, 72);\n"
"    border: 3px solid rgb(52, 59, 72);    \n"
"    background-image: url(:/16x16/icons/16x16/cil-check-alt.png);\n"
"}\n"
"\n"
"/* RADIO BUTTON */\n"
"QRadioButton::indicator {\n"
"    border: 3px solid rgb(52, 59, 72);\n"
"    width: 15px;\n"
"    height: 15px;\n"
"    border-radius: 10px;\n"
"    background: rgb(44, 49, 60);\n"
"}\n"
"QRadioButton::indicator:hover {\n"
"    border: 3px solid rgb(58, 66, 81);\n"
"}\n"
"QRadioButton::indicator:checked {\n"
"    background: 3px solid rgb(94, 106, 130);\n"
"    border: 3px solid rgb(52, 59, 72);    \n"
"}\n"
"\n"
"/* COMBOBOX */\n"
"QComboBox{\n"
"    background-color: rgb(27, 29, 35);\n"
"    border-radius: 5px;\n"
"    border: 2px solid rgb(27, 29, 35);\n"
"    padding: 5px;\n"
"    padding-left: 10px;\n"
"}\n"
"QComboBox:hover{\n"
"    border: 2px solid rgb(64, 71, 88);\n"
"}\n"
"QComboBox::drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    width: 25px; \n"
"    border-left-width: 3px;\n"
"    border-left-color: rgba(39, 44, 54, 150);\n"
"    border-left-style: solid;\n"
"    border-top-right-radius: 3px;\n"
"    border-bottom-right-radius: 3px;    \n"
"    background-image: url(:/16x16/icons/16x16/cil-arrow-bottom.png);\n"
"    background-position: center;\n"
"    background-repeat: no-reperat;\n"
" }\n"
"QComboBox QAbstractItemView {\n"
"    color: rgb(85, 170, 255);    \n"
"    background-color: rgb(27, 29, 35);\n"
"    padding: 10px;\n"
"    selection-background-color: rgb(39, 44, 54);\n"
"}\n"
"\n"
"/* SLIDERS */\n"
"QSlider::groove:horizontal {\n"
"    border-radius: 9px;\n"
"    height: 18px;\n"
"    margin: 0px;\n"
"    background-color: rgb(52, 59, 72);\n"
"}\n"
"QSlider::groove:horizontal:hover {\n"
"    background-color: rgb(55, 62, 76);\n"
"}\n"
"QSlider::handle:horizontal {\n"
"    background-color: rgb(85, 170, 255);\n"
"    border: none;\n"
"    height: 18px;\n"
"    width: 18px;\n"
"    margin: 0px;\n"
"    border-radius: 9px;\n"
"}\n"
"QSlider::handle:horizontal:hover {\n"
"    background-color: rgb(105, 180, 255);\n"
"}\n"
"QSlider::handle:horizontal:pressed {\n"
"    background-color: rgb(65, 130, 195);\n"
"}\n"
"\n"
"QSlider::groove:vertical {\n"
"    border-radius: 9px;\n"
"    width: 18px;\n"
"    margin: 0px;\n"
"    background-color: rgb(52, 59, 72);\n"
"}\n"
"QSlider::groove:vertical:hover {\n"
"    background-color: rgb(55, 62, 76);\n"
"}\n"
"QSlider::handle:vertical {\n"
"    background-color: rgb(85, 170, 255);\n"
"    border: none;\n"
"    height: 18px;\n"
"    width: 18px;\n"
"    margin: 0px;\n"
"    border-radius: 9px;\n"
"}\n"
"QSlider::handle:vertical:hover {\n"
"    background-color: rgb(105, 180, 255);\n"
"}\n"
"QSlider::handle:vertical:pressed {\n"
"    background-color: rgb(65, 130, 195);\n"
"}\n"
"/* QTableWidget*/\n"
"QTableWidget {    \n"
"    background-color: rgb(38, 44, 53);\n"
"    padding: 10px;\n"
"    border-radius: 15px;\n"
"    gridline-color: rgb(44, 49, 60);\n"
"    border-bottom: 1px solid rgb(44, 49, 60);\n"
"}\n"
"QTableWidget::item{\n"
"    border-color: rgb(44, 49, 60);\n"
"    padding-left: 5px;\n"
"    padding-right: 5px;\n"
"    gridline-color: rgb(44, 49, 60);\n"
"}\n"
"QTableWidget::item:selected{\n"
"    background-color: rgb(85, 170, 255);\n"
"}\n"
"QScrollBar:horizontal {\n"
"    border: none;\n"
"    background: rgb(52, 59, 72);\n"
"    height: 14px;\n"
"    margin: 0px 21px 0 21px;\n"
"    border-radius: 0px;\n"
"}\n"
"\n"
"QScrollBar:handle:horizontal {\n"
"    background: rgb(91, 101, 124);\n"
"\n"
"}\n"
"\n"
" QScrollBar:vertical {\n"
"    border: none;\n"
"    background: rgb(52, 59, 72);\n"
"    width: 14px;\n"
"    margin: 21px 0 21px 0;\n"
"    border-radius: 0px;\n"
" }\n"
"QHeaderView::section{\n"
"    Background-color: rgb(39, 44, 54);\n"
"    max-width: 30px;\n"
"    border: 1px solid rgb(44, 49, 60);\n"
"    border-style: none;\n"
"    border-bottom: 1px solid rgb(44, 49, 60);\n"
"    border-right: 1px solid rgb(44, 49, 60);\n"
"}\n"
"QTableWidget::horizontalHeader {    \n"
"    background-color: rgb(190, 190, 190);\n"
"}\n"
"\n"
"QHeaderView::section:horizontal\n"
"{\n"
"    background-color: rgb(51, 59, 70);\n"
"    padding: 3px;\n"
"    border-top-left-radius: 7px;\n"
"    border-top-right-radius: 7px;\n"
"    color: rgb(167,    174, 183);\n"
"}\n"
"QHeaderView::section:vertical\n"
"{\n"
"    border: 1px solid rgb(44, 49, 60);\n"
"}\n"
"\n"
"QScrollBar:handle:vertical {\n"
"    background: rgb(91, 101, 124);\n"
"\n"
"}\n"
"\n"
"QTableCornerButton::section{ \n"
"\n"
"    background-color: rgb(38, 44, 53);\n"
"}\n"
"\n"
"")
        self.ECP_frame_MainWindow.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.ECP_frame_MainWindow.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ECP_frame_MainWindow.setObjectName("ECP_frame_MainWindow")
        self.gridLayout_52 = QtWidgets.QGridLayout(self.ECP_frame_MainWindow)
        self.gridLayout_52.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_52.setSpacing(7)
        self.gridLayout_52.setObjectName("gridLayout_52")
        self.gridLayout_ECP_Total = QtWidgets.QGridLayout()
        self.gridLayout_ECP_Total.setSpacing(0)
        self.gridLayout_ECP_Total.setObjectName("gridLayout_ECP_Total")
        self.ECP_Main02 = QtWidgets.QFrame(self.ECP_frame_MainWindow)
        self.ECP_Main02.setFrameShape(QtWidgets.QFrame.Box)
        self.ECP_Main02.setFrameShadow(QtWidgets.QFrame.Plain)
        self.ECP_Main02.setLineWidth(0)
        self.ECP_Main02.setObjectName("ECP_Main02")
        self.layoutECP0005_2 = QtWidgets.QGridLayout(self.ECP_Main02)
        self.layoutECP0005_2.setContentsMargins(9, 3, 9, 3)
        self.layoutECP0005_2.setSpacing(6)
        self.layoutECP0005_2.setObjectName("layoutECP0005_2")
        self.ECP_Main03Grid = QtWidgets.QGridLayout()
        self.ECP_Main03Grid.setSpacing(3)
        self.ECP_Main03Grid.setObjectName("ECP_Main03Grid")
        self.gridLayout_ECP02_I04 = QtWidgets.QGridLayout()
        self.gridLayout_ECP02_I04.setSpacing(0)
        self.gridLayout_ECP02_I04.setObjectName("gridLayout_ECP02_I04")
        spacerItem = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.gridLayout_ECP02_I04.addItem(spacerItem, 0, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.gridLayout_ECP02_I04.addItem(spacerItem1, 2, 0, 1, 1)
        self.ECP_Input04 = QtWidgets.QDoubleSpinBox(self.ECP_Main02)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ECP_Input04.sizePolicy().hasHeightForWidth())
        self.ECP_Input04.setSizePolicy(sizePolicy)
        self.ECP_Input04.setMinimumSize(QtCore.QSize(0, 0))
        self.ECP_Input04.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.ECP_Input04.setFont(font)
        self.ECP_Input04.setStyleSheet("padding: 3px;")
        self.ECP_Input04.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.ECP_Input04.setProperty("showGroupSeparator", True)
        self.ECP_Input04.setMaximum(100000.0)
        self.ECP_Input04.setStepType(QtWidgets.QAbstractSpinBox.DefaultStepType)
        self.ECP_Input04.setProperty("value", 0.0)
        self.ECP_Input04.setObjectName("ECP_Input04")
        self.gridLayout_ECP02_I04.addWidget(self.ECP_Input04, 1, 0, 1, 1)
        self.ECP_Main03Grid.addLayout(self.gridLayout_ECP02_I04, 3, 2, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(5, 5, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.ECP_Main03Grid.addItem(spacerItem2, 1, 0, 8, 1)
        self.gridLayout_ECP02_I05 = QtWidgets.QGridLayout()
        self.gridLayout_ECP02_I05.setSpacing(0)
        self.gridLayout_ECP02_I05.setObjectName("gridLayout_ECP02_I05")
        spacerItem3 = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.gridLayout_ECP02_I05.addItem(spacerItem3, 0, 0, 1, 1)
        self.ECP_Input05 = QtWidgets.QDoubleSpinBox(self.ECP_Main02)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ECP_Input05.sizePolicy().hasHeightForWidth())
        self.ECP_Input05.setSizePolicy(sizePolicy)
        self.ECP_Input05.setMinimumSize(QtCore.QSize(0, 0))
        self.ECP_Input05.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.ECP_Input05.setFont(font)
        self.ECP_Input05.setStyleSheet("padding: 3px;")
        self.ECP_Input05.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.ECP_Input05.setMinimum(-273.0)
        self.ECP_Input05.setMaximum(3000.0)
        self.ECP_Input05.setObjectName("ECP_Input05")
        self.gridLayout_ECP02_I05.addWidget(self.ECP_Input05, 1, 0, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.gridLayout_ECP02_I05.addItem(spacerItem4, 2, 0, 1, 1)
        self.ECP_Main03Grid.addLayout(self.gridLayout_ECP02_I05, 4, 2, 1, 1)
        self.LabelSub_ECP09 = QtWidgets.QLabel(self.ECP_Main02)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LabelSub_ECP09.sizePolicy().hasHeightForWidth())
        self.LabelSub_ECP09.setSizePolicy(sizePolicy)
        self.LabelSub_ECP09.setMinimumSize(QtCore.QSize(100, 0))
        self.LabelSub_ECP09.setSizeIncrement(QtCore.QSize(1, 0))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.LabelSub_ECP09.setFont(font)
        self.LabelSub_ECP09.setObjectName("LabelSub_ECP09")
        self.ECP_Main03Grid.addWidget(self.LabelSub_ECP09, 8, 1, 1, 1)
        self.gridLayout_ECP02_I06 = QtWidgets.QGridLayout()
        self.gridLayout_ECP02_I06.setSpacing(0)
        self.gridLayout_ECP02_I06.setObjectName("gridLayout_ECP02_I06")
        spacerItem5 = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.gridLayout_ECP02_I06.addItem(spacerItem5, 0, 0, 1, 1)
        self.ECP_Input06 = QtWidgets.QDoubleSpinBox(self.ECP_Main02)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ECP_Input06.sizePolicy().hasHeightForWidth())
        self.ECP_Input06.setSizePolicy(sizePolicy)
        self.ECP_Input06.setMinimumSize(QtCore.QSize(0, 0))
        self.ECP_Input06.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.ECP_Input06.setFont(font)
        self.ECP_Input06.setStyleSheet("padding: 3px;")
        self.ECP_Input06.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.ECP_Input06.setProperty("showGroupSeparator", True)
        self.ECP_Input06.setDecimals(5)
        self.ECP_Input06.setMinimum(0.9)
        self.ECP_Input06.setMaximum(1.1)
        self.ECP_Input06.setSingleStep(0.001)
        self.ECP_Input06.setStepType(QtWidgets.QAbstractSpinBox.DefaultStepType)
        self.ECP_Input06.setProperty("value", 1.0)
        self.ECP_Input06.setObjectName("ECP_Input06")
        self.gridLayout_ECP02_I06.addWidget(self.ECP_Input06, 1, 0, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.gridLayout_ECP02_I06.addItem(spacerItem6, 2, 0, 1, 1)
        self.ECP_Main03Grid.addLayout(self.gridLayout_ECP02_I06, 5, 2, 1, 1)
        self.gridLayout_ECP02_I08 = QtWidgets.QGridLayout()
        self.gridLayout_ECP02_I08.setSpacing(0)
        self.gridLayout_ECP02_I08.setObjectName("gridLayout_ECP02_I08")
        spacerItem7 = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.gridLayout_ECP02_I08.addItem(spacerItem7, 0, 0, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.gridLayout_ECP02_I08.addItem(spacerItem8, 2, 0, 1, 1)
        self.ECP_Input08 = QtWidgets.QDoubleSpinBox(self.ECP_Main02)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ECP_Input08.sizePolicy().hasHeightForWidth())
        self.ECP_Input08.setSizePolicy(sizePolicy)
        self.ECP_Input08.setMinimumSize(QtCore.QSize(0, 0))
        self.ECP_Input08.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.ECP_Input08.setFont(font)
        self.ECP_Input08.setStyleSheet("padding: 3px;")
        self.ECP_Input08.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.ECP_Input08.setProperty("showGroupSeparator", True)
        self.ECP_Input08.setMaximum(1000.0)
        self.ECP_Input08.setStepType(QtWidgets.QAbstractSpinBox.DefaultStepType)
        self.ECP_Input08.setProperty("value", 381.0)
        self.ECP_Input08.setObjectName("ECP_Input08")
        self.gridLayout_ECP02_I08.addWidget(self.ECP_Input08, 1, 0, 1, 1)
        self.ECP_Main03Grid.addLayout(self.gridLayout_ECP02_I08, 7, 2, 1, 1)
        self.gridLayout_ECP02_I03 = QtWidgets.QGridLayout()
        self.gridLayout_ECP02_I03.setSpacing(0)
        self.gridLayout_ECP02_I03.setObjectName("gridLayout_ECP02_I03")
        spacerItem9 = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.gridLayout_ECP02_I03.addItem(spacerItem9, 2, 0, 1, 1)
        spacerItem10 = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.gridLayout_ECP02_I03.addItem(spacerItem10, 0, 0, 1, 1)
        self.ECP_Input03 = QtWidgets.QDoubleSpinBox(self.ECP_Main02)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ECP_Input03.sizePolicy().hasHeightForWidth())
        self.ECP_Input03.setSizePolicy(sizePolicy)
        self.ECP_Input03.setMinimumSize(QtCore.QSize(0, 0))
        self.ECP_Input03.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.ECP_Input03.setFont(font)
        self.ECP_Input03.setStyleSheet("padding: 3px;")
        self.ECP_Input03.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.ECP_Input03.setSuffix("")
        self.ECP_Input03.setMaximum(100.0)
        self.ECP_Input03.setProperty("value", 100.0)
        self.ECP_Input03.setObjectName("ECP_Input03")
        self.gridLayout_ECP02_I03.addWidget(self.ECP_Input03, 1, 0, 1, 1)
        self.ECP_Main03Grid.addLayout(self.gridLayout_ECP02_I03, 2, 2, 1, 1)
        self.gridLayout_ECP02_I09 = QtWidgets.QGridLayout()
        self.gridLayout_ECP02_I09.setSpacing(0)
        self.gridLayout_ECP02_I09.setObjectName("gridLayout_ECP02_I09")
        spacerItem11 = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.gridLayout_ECP02_I09.addItem(spacerItem11, 0, 0, 1, 1)
        spacerItem12 = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.gridLayout_ECP02_I09.addItem(spacerItem12, 2, 0, 1, 1)
        self.ECP_Input09 = QtWidgets.QDoubleSpinBox(self.ECP_Main02)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ECP_Input09.sizePolicy().hasHeightForWidth())
        self.ECP_Input09.setSizePolicy(sizePolicy)
        self.ECP_Input09.setMinimumSize(QtCore.QSize(0, 0))
        self.ECP_Input09.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.ECP_Input09.setFont(font)
        self.ECP_Input09.setStyleSheet("padding: 3px;")
        self.ECP_Input09.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.ECP_Input09.setProperty("showGroupSeparator", True)
        self.ECP_Input09.setMaximum(1000.0)
        self.ECP_Input09.setStepType(QtWidgets.QAbstractSpinBox.DefaultStepType)
        self.ECP_Input09.setProperty("value", 381.0)
        self.ECP_Input09.setObjectName("ECP_Input09")
        self.gridLayout_ECP02_I09.addWidget(self.ECP_Input09, 1, 0, 1, 1)
        self.ECP_Main03Grid.addLayout(self.gridLayout_ECP02_I09, 8, 2, 1, 1)
        self.LabelSub_ECP06 = QtWidgets.QLabel(self.ECP_Main02)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LabelSub_ECP06.sizePolicy().hasHeightForWidth())
        self.LabelSub_ECP06.setSizePolicy(sizePolicy)
        self.LabelSub_ECP06.setMinimumSize(QtCore.QSize(100, 0))
        self.LabelSub_ECP06.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.LabelSub_ECP06.setSizeIncrement(QtCore.QSize(1, 0))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.LabelSub_ECP06.setFont(font)
        self.LabelSub_ECP06.setObjectName("LabelSub_ECP06")
        self.ECP_Main03Grid.addWidget(self.LabelSub_ECP06, 5, 1, 1, 1)
        self.gridLayout_ECP02_I01 = QtWidgets.QGridLayout()
        self.gridLayout_ECP02_I01.setObjectName("gridLayout_ECP02_I01")
        spacerItem13 = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.gridLayout_ECP02_I01.addItem(spacerItem13, 2, 0, 1, 1)
        spacerItem14 = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.gridLayout_ECP02_I01.addItem(spacerItem14, 0, 0, 1, 1)
        self.ECP_Input01 = QtWidgets.QDateTimeEdit(self.ECP_Main02)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ECP_Input01.sizePolicy().hasHeightForWidth())
        self.ECP_Input01.setSizePolicy(sizePolicy)
        self.ECP_Input01.setMinimumSize(QtCore.QSize(1, 0))
        self.ECP_Input01.setDateTime(QtCore.QDateTime(QtCore.QDate(2020, 1, 1), QtCore.QTime(0, 0, 0)))
        self.ECP_Input01.setCurrentSection(QtWidgets.QDateTimeEdit.YearSection)
        self.ECP_Input01.setObjectName("ECP_Input01")
        self.gridLayout_ECP02_I01.addWidget(self.ECP_Input01, 1, 0, 1, 1)
        self.ECP_Main03Grid.addLayout(self.gridLayout_ECP02_I01, 1, 2, 1, 1)
        self.LabelSub_ECP04 = QtWidgets.QLabel(self.ECP_Main02)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LabelSub_ECP04.sizePolicy().hasHeightForWidth())
        self.LabelSub_ECP04.setSizePolicy(sizePolicy)
        self.LabelSub_ECP04.setMinimumSize(QtCore.QSize(100, 0))
        self.LabelSub_ECP04.setSizeIncrement(QtCore.QSize(1, 0))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.LabelSub_ECP04.setFont(font)
        self.LabelSub_ECP04.setObjectName("LabelSub_ECP04")
        self.ECP_Main03Grid.addWidget(self.LabelSub_ECP04, 3, 1, 1, 1)
        self.LabelSub_ECP05 = QtWidgets.QLabel(self.ECP_Main02)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LabelSub_ECP05.sizePolicy().hasHeightForWidth())
        self.LabelSub_ECP05.setSizePolicy(sizePolicy)
        self.LabelSub_ECP05.setMinimumSize(QtCore.QSize(100, 0))
        self.LabelSub_ECP05.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.LabelSub_ECP05.setSizeIncrement(QtCore.QSize(1, 0))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.LabelSub_ECP05.setFont(font)
        self.LabelSub_ECP05.setObjectName("LabelSub_ECP05")
        self.ECP_Main03Grid.addWidget(self.LabelSub_ECP05, 4, 1, 1, 1)
        self.LabelSub_ECP03 = QtWidgets.QLabel(self.ECP_Main02)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LabelSub_ECP03.sizePolicy().hasHeightForWidth())
        self.LabelSub_ECP03.setSizePolicy(sizePolicy)
        self.LabelSub_ECP03.setMinimumSize(QtCore.QSize(100, 0))
        self.LabelSub_ECP03.setSizeIncrement(QtCore.QSize(1, 0))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.LabelSub_ECP03.setFont(font)
        self.LabelSub_ECP03.setObjectName("LabelSub_ECP03")
        self.ECP_Main03Grid.addWidget(self.LabelSub_ECP03, 2, 1, 1, 1)
        self.ECP_Input02_Title_2 = QtWidgets.QLabel(self.ECP_Main02)
        self.ECP_Input02_Title_2.setMinimumSize(QtCore.QSize(0, 0))
        self.ECP_Input02_Title_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.ECP_Input02_Title_2.setFont(font)
        self.ECP_Input02_Title_2.setObjectName("ECP_Input02_Title_2")
        self.ECP_Main03Grid.addWidget(self.ECP_Input02_Title_2, 0, 0, 1, 3)
        self.LabelSub_ECP01 = QtWidgets.QLabel(self.ECP_Main02)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LabelSub_ECP01.sizePolicy().hasHeightForWidth())
        self.LabelSub_ECP01.setSizePolicy(sizePolicy)
        self.LabelSub_ECP01.setMinimumSize(QtCore.QSize(100, 0))
        self.LabelSub_ECP01.setSizeIncrement(QtCore.QSize(1, 0))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.LabelSub_ECP01.setFont(font)
        self.LabelSub_ECP01.setObjectName("LabelSub_ECP01")
        self.ECP_Main03Grid.addWidget(self.LabelSub_ECP01, 1, 1, 1, 1)
        self.LabelSub_ECP08 = QtWidgets.QLabel(self.ECP_Main02)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LabelSub_ECP08.sizePolicy().hasHeightForWidth())
        self.LabelSub_ECP08.setSizePolicy(sizePolicy)
        self.LabelSub_ECP08.setMinimumSize(QtCore.QSize(100, 0))
        self.LabelSub_ECP08.setSizeIncrement(QtCore.QSize(1, 0))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.LabelSub_ECP08.setFont(font)
        self.LabelSub_ECP08.setObjectName("LabelSub_ECP08")
        self.ECP_Main03Grid.addWidget(self.LabelSub_ECP08, 7, 1, 1, 1)
        self.LabelSub_ECP07 = QtWidgets.QLabel(self.ECP_Main02)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LabelSub_ECP07.sizePolicy().hasHeightForWidth())
        self.LabelSub_ECP07.setSizePolicy(sizePolicy)
        self.LabelSub_ECP07.setMinimumSize(QtCore.QSize(100, 0))
        self.LabelSub_ECP07.setSizeIncrement(QtCore.QSize(1, 0))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.LabelSub_ECP07.setFont(font)
        self.LabelSub_ECP07.setObjectName("LabelSub_ECP07")
        self.ECP_Main03Grid.addWidget(self.LabelSub_ECP07, 6, 1, 1, 1)
        self.gridLayout_ECP02_I07 = QtWidgets.QGridLayout()
        self.gridLayout_ECP02_I07.setSpacing(0)
        self.gridLayout_ECP02_I07.setObjectName("gridLayout_ECP02_I07")
        spacerItem15 = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.gridLayout_ECP02_I07.addItem(spacerItem15, 0, 0, 1, 1)
        spacerItem16 = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.gridLayout_ECP02_I07.addItem(spacerItem16, 2, 0, 1, 1)
        self.ECP_Input07 = QtWidgets.QDoubleSpinBox(self.ECP_Main02)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ECP_Input07.sizePolicy().hasHeightForWidth())
        self.ECP_Input07.setSizePolicy(sizePolicy)
        self.ECP_Input07.setMinimumSize(QtCore.QSize(0, 0))
        self.ECP_Input07.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.ECP_Input07.setFont(font)
        self.ECP_Input07.setStyleSheet("padding: 3px;")
        self.ECP_Input07.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.ECP_Input07.setProperty("showGroupSeparator", True)
        self.ECP_Input07.setMaximum(1000.0)
        self.ECP_Input07.setStepType(QtWidgets.QAbstractSpinBox.DefaultStepType)
        self.ECP_Input07.setProperty("value", 381.0)
        self.ECP_Input07.setObjectName("ECP_Input07")
        self.gridLayout_ECP02_I07.addWidget(self.ECP_Input07, 1, 0, 1, 1)
        self.ECP_Main03Grid.addLayout(self.gridLayout_ECP02_I07, 6, 2, 1, 1)
        self.layoutECP0005_2.addLayout(self.ECP_Main03Grid, 0, 0, 1, 1)
        self.gridLayout_ECP_Total.addWidget(self.ECP_Main02, 1, 0, 1, 1)
        self.ECP_Main01 = QtWidgets.QFrame(self.ECP_frame_MainWindow)
        self.ECP_Main01.setFrameShape(QtWidgets.QFrame.Box)
        self.ECP_Main01.setFrameShadow(QtWidgets.QFrame.Plain)
        self.ECP_Main01.setLineWidth(0)
        self.ECP_Main01.setObjectName("ECP_Main01")
        self.layoutECP0002 = QtWidgets.QGridLayout(self.ECP_Main01)
        self.layoutECP0002.setContentsMargins(9, 3, 9, 3)
        self.layoutECP0002.setObjectName("layoutECP0002")
        self.ECP_Main02Grid = QtWidgets.QGridLayout()
        self.ECP_Main02Grid.setContentsMargins(0, 0, 0, 0)
        self.ECP_Main02Grid.setSpacing(3)
        self.ECP_Main02Grid.setObjectName("ECP_Main02Grid")
        self.ECP_CalcTarget02 = QtWidgets.QRadioButton(self.ECP_Main01)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ECP_CalcTarget02.sizePolicy().hasHeightForWidth())
        self.ECP_CalcTarget02.setSizePolicy(sizePolicy)
        self.ECP_CalcTarget02.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.ECP_CalcTarget02.setFont(font)
        self.ECP_CalcTarget02.setAutoExclusive(False)
        self.ECP_CalcTarget02.setObjectName("ECP_CalcTarget02")
        self.ECP_Main02Grid.addWidget(self.ECP_CalcTarget02, 2, 1, 1, 1)
        self.ECP_CalcTarget01 = QtWidgets.QRadioButton(self.ECP_Main01)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ECP_CalcTarget01.sizePolicy().hasHeightForWidth())
        self.ECP_CalcTarget01.setSizePolicy(sizePolicy)
        self.ECP_CalcTarget01.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.ECP_CalcTarget01.setFont(font)
        self.ECP_CalcTarget01.setStatusTip("")
        self.ECP_CalcTarget01.setWhatsThis("")
        self.ECP_CalcTarget01.setAutoExclusive(False)
        self.ECP_CalcTarget01.setObjectName("ECP_CalcTarget01")
        self.ECP_Main02Grid.addWidget(self.ECP_CalcTarget01, 1, 1, 1, 1)
        spacerItem17 = QtWidgets.QSpacerItem(1, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.ECP_Main02Grid.addItem(spacerItem17, 1, 0, 2, 1)
        self.LabelTitle_ECP02 = QtWidgets.QLabel(self.ECP_Main01)
        self.LabelTitle_ECP02.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.LabelTitle_ECP02.setFont(font)
        self.LabelTitle_ECP02.setObjectName("LabelTitle_ECP02")
        self.ECP_Main02Grid.addWidget(self.LabelTitle_ECP02, 0, 0, 1, 3)
        spacerItem18 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.ECP_Main02Grid.addItem(spacerItem18, 1, 2, 2, 1)
        self.layoutECP0002.addLayout(self.ECP_Main02Grid, 0, 0, 1, 1)
        self.gridLayout_ECP_Total.addWidget(self.ECP_Main01, 0, 0, 1, 1)
        spacerItem19 = QtWidgets.QSpacerItem(20, 400, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_ECP_Total.addItem(spacerItem19, 3, 0, 1, 1)
        self.ECP_Main03 = QtWidgets.QFrame(self.ECP_frame_MainWindow)
        self.ECP_Main03.setFrameShape(QtWidgets.QFrame.Box)
        self.ECP_Main03.setFrameShadow(QtWidgets.QFrame.Plain)
        self.ECP_Main03.setLineWidth(0)
        self.ECP_Main03.setObjectName("ECP_Main03")
        self.layoutECP0007 = QtWidgets.QGridLayout(self.ECP_Main03)
        self.layoutECP0007.setContentsMargins(9, 3, 9, 3)
        self.layoutECP0007.setObjectName("layoutECP0007")
        self.ECP_Main04Grid = QtWidgets.QGridLayout()
        self.ECP_Main04Grid.setSpacing(3)
        self.ECP_Main04Grid.setObjectName("ECP_Main04Grid")
        self.LabelSub_ECP15 = QtWidgets.QLabel(self.ECP_Main03)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LabelSub_ECP15.sizePolicy().hasHeightForWidth())
        self.LabelSub_ECP15.setSizePolicy(sizePolicy)
        self.LabelSub_ECP15.setMinimumSize(QtCore.QSize(100, 0))
        self.LabelSub_ECP15.setSizeIncrement(QtCore.QSize(1, 0))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.LabelSub_ECP15.setFont(font)
        self.LabelSub_ECP15.setObjectName("LabelSub_ECP15")
        self.ECP_Main04Grid.addWidget(self.LabelSub_ECP15, 4, 1, 1, 1)
        spacerItem20 = QtWidgets.QSpacerItem(5, 5, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.ECP_Main04Grid.addItem(spacerItem20, 1, 0, 6, 1)
        self.gridLayout_ECP03_I06 = QtWidgets.QGridLayout()
        self.gridLayout_ECP03_I06.setSpacing(0)
        self.gridLayout_ECP03_I06.setObjectName("gridLayout_ECP03_I06")
        spacerItem21 = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.gridLayout_ECP03_I06.addItem(spacerItem21, 2, 0, 1, 1)
        spacerItem22 = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.gridLayout_ECP03_I06.addItem(spacerItem22, 0, 0, 1, 1)
        self.ECP_Input16 = QtWidgets.QDoubleSpinBox(self.ECP_Main03)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ECP_Input16.sizePolicy().hasHeightForWidth())
        self.ECP_Input16.setSizePolicy(sizePolicy)
        self.ECP_Input16.setMinimumSize(QtCore.QSize(0, 0))
        self.ECP_Input16.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.ECP_Input16.setSizeIncrement(QtCore.QSize(1, 0))
        self.ECP_Input16.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.ECP_Input16.setFont(font)
        self.ECP_Input16.setStyleSheet("padding: 3px;")
        self.ECP_Input16.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.ECP_Input16.setProperty("showGroupSeparator", True)
        self.ECP_Input16.setMaximum(1000.0)
        self.ECP_Input16.setStepType(QtWidgets.QAbstractSpinBox.DefaultStepType)
        self.ECP_Input16.setProperty("value", 381.0)
        self.ECP_Input16.setObjectName("ECP_Input16")
        self.gridLayout_ECP03_I06.addWidget(self.ECP_Input16, 1, 0, 1, 1)
        self.ECP_Main04Grid.addLayout(self.gridLayout_ECP03_I06, 5, 2, 1, 1)
        self.LabelSub_ECP14 = QtWidgets.QLabel(self.ECP_Main03)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LabelSub_ECP14.sizePolicy().hasHeightForWidth())
        self.LabelSub_ECP14.setSizePolicy(sizePolicy)
        self.LabelSub_ECP14.setMinimumSize(QtCore.QSize(100, 0))
        self.LabelSub_ECP14.setSizeIncrement(QtCore.QSize(1, 0))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.LabelSub_ECP14.setFont(font)
        self.LabelSub_ECP14.setObjectName("LabelSub_ECP14")
        self.ECP_Main04Grid.addWidget(self.LabelSub_ECP14, 3, 1, 1, 1)
        self.LabelSub_ECP16 = QtWidgets.QLabel(self.ECP_Main03)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LabelSub_ECP16.sizePolicy().hasHeightForWidth())
        self.LabelSub_ECP16.setSizePolicy(sizePolicy)
        self.LabelSub_ECP16.setMinimumSize(QtCore.QSize(100, 0))
        self.LabelSub_ECP16.setSizeIncrement(QtCore.QSize(1, 0))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.LabelSub_ECP16.setFont(font)
        self.LabelSub_ECP16.setObjectName("LabelSub_ECP16")
        self.ECP_Main04Grid.addWidget(self.LabelSub_ECP16, 5, 1, 1, 1)
        self.gridLayout_ECP03_I04 = QtWidgets.QGridLayout()
        self.gridLayout_ECP03_I04.setSpacing(0)
        self.gridLayout_ECP03_I04.setObjectName("gridLayout_ECP03_I04")
        spacerItem23 = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.gridLayout_ECP03_I04.addItem(spacerItem23, 2, 0, 1, 1)
        spacerItem24 = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.gridLayout_ECP03_I04.addItem(spacerItem24, 0, 0, 1, 1)
        self.ECP_Input14 = QtWidgets.QDoubleSpinBox(self.ECP_Main03)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ECP_Input14.sizePolicy().hasHeightForWidth())
        self.ECP_Input14.setSizePolicy(sizePolicy)
        self.ECP_Input14.setMinimumSize(QtCore.QSize(0, 0))
        self.ECP_Input14.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.ECP_Input14.setSizeIncrement(QtCore.QSize(1, 0))
        self.ECP_Input14.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.ECP_Input14.setFont(font)
        self.ECP_Input14.setStyleSheet("padding: 3px;")
        self.ECP_Input14.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.ECP_Input14.setProperty("showGroupSeparator", True)
        self.ECP_Input14.setMaximum(1000.0)
        self.ECP_Input14.setStepType(QtWidgets.QAbstractSpinBox.DefaultStepType)
        self.ECP_Input14.setProperty("value", 381.0)
        self.ECP_Input14.setObjectName("ECP_Input14")
        self.gridLayout_ECP03_I04.addWidget(self.ECP_Input14, 1, 0, 1, 1)
        self.ECP_Main04Grid.addLayout(self.gridLayout_ECP03_I04, 3, 2, 1, 1)
        self.gridLayout_ECP03_I01 = QtWidgets.QGridLayout()
        self.gridLayout_ECP03_I01.setObjectName("gridLayout_ECP03_I01")
        spacerItem25 = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.gridLayout_ECP03_I01.addItem(spacerItem25, 0, 0, 1, 1)
        spacerItem26 = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.gridLayout_ECP03_I01.addItem(spacerItem26, 2, 0, 1, 1)
        self.ECP_Input11 = QtWidgets.QDateTimeEdit(self.ECP_Main03)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ECP_Input11.sizePolicy().hasHeightForWidth())
        self.ECP_Input11.setSizePolicy(sizePolicy)
        self.ECP_Input11.setSizeIncrement(QtCore.QSize(1, 0))
        self.ECP_Input11.setDateTime(QtCore.QDateTime(QtCore.QDate(2020, 1, 1), QtCore.QTime(0, 0, 0)))
        self.ECP_Input11.setObjectName("ECP_Input11")
        self.gridLayout_ECP03_I01.addWidget(self.ECP_Input11, 1, 0, 1, 1)
        self.ECP_Main04Grid.addLayout(self.gridLayout_ECP03_I01, 1, 2, 1, 1)
        self.LabelSub_ECP11 = QtWidgets.QLabel(self.ECP_Main03)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LabelSub_ECP11.sizePolicy().hasHeightForWidth())
        self.LabelSub_ECP11.setSizePolicy(sizePolicy)
        self.LabelSub_ECP11.setMinimumSize(QtCore.QSize(100, 0))
        self.LabelSub_ECP11.setSizeIncrement(QtCore.QSize(1, 0))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.LabelSub_ECP11.setFont(font)
        self.LabelSub_ECP11.setObjectName("LabelSub_ECP11")
        self.ECP_Main04Grid.addWidget(self.LabelSub_ECP11, 1, 1, 1, 1)
        self.gridLayout_ECP03_I05 = QtWidgets.QGridLayout()
        self.gridLayout_ECP03_I05.setSpacing(0)
        self.gridLayout_ECP03_I05.setObjectName("gridLayout_ECP03_I05")
        spacerItem27 = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.gridLayout_ECP03_I05.addItem(spacerItem27, 2, 0, 1, 1)
        spacerItem28 = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.gridLayout_ECP03_I05.addItem(spacerItem28, 0, 0, 1, 1)
        self.ECP_Input15 = QtWidgets.QDoubleSpinBox(self.ECP_Main03)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ECP_Input15.sizePolicy().hasHeightForWidth())
        self.ECP_Input15.setSizePolicy(sizePolicy)
        self.ECP_Input15.setMinimumSize(QtCore.QSize(0, 0))
        self.ECP_Input15.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.ECP_Input15.setSizeIncrement(QtCore.QSize(1, 0))
        self.ECP_Input15.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.ECP_Input15.setFont(font)
        self.ECP_Input15.setStyleSheet("padding: 3px;")
        self.ECP_Input15.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.ECP_Input15.setProperty("showGroupSeparator", True)
        self.ECP_Input15.setMaximum(1000.0)
        self.ECP_Input15.setStepType(QtWidgets.QAbstractSpinBox.DefaultStepType)
        self.ECP_Input15.setProperty("value", 381.0)
        self.ECP_Input15.setObjectName("ECP_Input15")
        self.gridLayout_ECP03_I05.addWidget(self.ECP_Input15, 1, 0, 1, 1)
        self.ECP_Main04Grid.addLayout(self.gridLayout_ECP03_I05, 4, 2, 1, 1)
        self.LabelTitle_ECP06 = QtWidgets.QLabel(self.ECP_Main03)
        self.LabelTitle_ECP06.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.LabelTitle_ECP06.setFont(font)
        self.LabelTitle_ECP06.setObjectName("LabelTitle_ECP06")
        self.ECP_Main04Grid.addWidget(self.LabelTitle_ECP06, 0, 0, 1, 3)
        self.LabelSub_ECP13 = QtWidgets.QLabel(self.ECP_Main03)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LabelSub_ECP13.sizePolicy().hasHeightForWidth())
        self.LabelSub_ECP13.setSizePolicy(sizePolicy)
        self.LabelSub_ECP13.setMinimumSize(QtCore.QSize(100, 0))
        self.LabelSub_ECP13.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.LabelSub_ECP13.setSizeIncrement(QtCore.QSize(1, 0))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.LabelSub_ECP13.setFont(font)
        self.LabelSub_ECP13.setObjectName("LabelSub_ECP13")
        self.ECP_Main04Grid.addWidget(self.LabelSub_ECP13, 2, 1, 1, 1)
        self.gridLayout_ECP03_I03 = QtWidgets.QGridLayout()
        self.gridLayout_ECP03_I03.setSpacing(0)
        self.gridLayout_ECP03_I03.setObjectName("gridLayout_ECP03_I03")
        self.ECP_Input13 = QtWidgets.QDoubleSpinBox(self.ECP_Main03)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ECP_Input13.sizePolicy().hasHeightForWidth())
        self.ECP_Input13.setSizePolicy(sizePolicy)
        self.ECP_Input13.setMinimumSize(QtCore.QSize(0, 0))
        self.ECP_Input13.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.ECP_Input13.setSizeIncrement(QtCore.QSize(1, 0))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.ECP_Input13.setFont(font)
        self.ECP_Input13.setStyleSheet("padding: 3px;")
        self.ECP_Input13.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.ECP_Input13.setProperty("showGroupSeparator", True)
        self.ECP_Input13.setMaximum(100000.0)
        self.ECP_Input13.setStepType(QtWidgets.QAbstractSpinBox.DefaultStepType)
        self.ECP_Input13.setProperty("value", 0.0)
        self.ECP_Input13.setObjectName("ECP_Input13")
        self.gridLayout_ECP03_I03.addWidget(self.ECP_Input13, 1, 0, 1, 1)
        spacerItem29 = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.gridLayout_ECP03_I03.addItem(spacerItem29, 0, 0, 1, 1)
        spacerItem30 = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.gridLayout_ECP03_I03.addItem(spacerItem30, 2, 0, 1, 1)
        self.ECP_Main04Grid.addLayout(self.gridLayout_ECP03_I03, 2, 2, 1, 1)
        self.layoutECP0007.addLayout(self.ECP_Main04Grid, 0, 0, 1, 1)
        self.gridLayout_ECP_Total.addWidget(self.ECP_Main03, 2, 0, 1, 1)
        self.ECP_Main08_CalcButton = QtWidgets.QFrame(self.ECP_frame_MainWindow)
        self.ECP_Main08_CalcButton.setMinimumSize(QtCore.QSize(0, 0))
        self.ECP_Main08_CalcButton.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.ECP_Main08_CalcButton.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ECP_Main08_CalcButton.setObjectName("ECP_Main08_CalcButton")
        self.ECP_CalcButton_Grid = QtWidgets.QGridLayout(self.ECP_Main08_CalcButton)
        self.ECP_CalcButton_Grid.setContentsMargins(0, 0, 0, 0)
        self.ECP_CalcButton_Grid.setSpacing(6)
        self.ECP_CalcButton_Grid.setObjectName("ECP_CalcButton_Grid")
        self.ECP_save_button = QtWidgets.QPushButton(self.ECP_Main08_CalcButton)
        self.ECP_save_button.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.ECP_save_button.setFont(font)
        self.ECP_save_button.setStyleSheet("QPushButton {\n"
"    border: 2px solid rgb(52, 59, 72);\n"
"    border-radius: 5px;\n"
"    background-color: rgb(52, 59, 72);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(57, 65, 79);\n"
"    border: 2px solid rgb(61, 70, 86);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgb(67, 77, 93);\n"
"    border: 2px solid rgb(43, 50, 61);\n"
"}")
        self.ECP_save_button.setObjectName("ECP_save_button")
        self.ECP_CalcButton_Grid.addWidget(self.ECP_save_button, 1, 0, 1, 1)
        self.ECP_run_button = QtWidgets.QPushButton(self.ECP_Main08_CalcButton)
        self.ECP_run_button.setMinimumSize(QtCore.QSize(200, 50))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.ECP_run_button.setFont(font)
        self.ECP_run_button.setStyleSheet("QPushButton {\n"
"    border: 2px solid rgb(52, 59, 72);\n"
"    border-radius: 5px;\n"
"    background-color: rgb(85, 170, 255);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(72, 144, 216);\n"
"    border: 2px solid rgb(61, 70, 86);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgb(52, 59, 72);\n"
"    border: 2px solid rgb(43, 50, 61);\n"
"}")
        self.ECP_run_button.setObjectName("ECP_run_button")
        self.ECP_CalcButton_Grid.addWidget(self.ECP_run_button, 1, 1, 1, 1)
        self.gridLayout_ECP_Total.addWidget(self.ECP_Main08_CalcButton, 4, 0, 1, 1)
        self.gridLayout_52.addLayout(self.gridLayout_ECP_Total, 0, 0, 2, 1)
        self.frame_ECP_TableWidget = QtWidgets.QFrame(self.ECP_frame_MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(200)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_ECP_TableWidget.sizePolicy().hasHeightForWidth())
        self.frame_ECP_TableWidget.setSizePolicy(sizePolicy)
        self.frame_ECP_TableWidget.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_ECP_TableWidget.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_ECP_TableWidget.setObjectName("frame_ECP_TableWidget")
        self.gridlayout_SD_TableWidget_4 = QtWidgets.QGridLayout(self.frame_ECP_TableWidget)
        self.gridlayout_SD_TableWidget_4.setObjectName("gridlayout_SD_TableWidget_4")
        self.ECP_widgetReport = QtWidgets.QWidget(self.frame_ECP_TableWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(10)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.ECP_widgetReport.sizePolicy().hasHeightForWidth())
        self.ECP_widgetReport.setSizePolicy(sizePolicy)
        self.ECP_widgetReport.setMinimumSize(QtCore.QSize(0, 0))
        self.ECP_widgetReport.setObjectName("ECP_widgetReport")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.ECP_widgetReport)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.frame_2 = QtWidgets.QFrame(self.ECP_widgetReport)
        self.frame_2.setMinimumSize(QtCore.QSize(100, 0))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_ECP_TableWidget_2 = QtWidgets.QFrame(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_ECP_TableWidget_2.sizePolicy().hasHeightForWidth())
        self.frame_ECP_TableWidget_2.setSizePolicy(sizePolicy)
        self.frame_ECP_TableWidget_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_ECP_TableWidget_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_ECP_TableWidget_2.setObjectName("frame_ECP_TableWidget_2")
        self.gridlayout_ECP_TableWidget = QtWidgets.QGridLayout(self.frame_ECP_TableWidget_2)
        self.gridlayout_ECP_TableWidget.setObjectName("gridlayout_ECP_TableWidget")
        self.verticalLayout_2.addWidget(self.frame_ECP_TableWidget_2)
        self.ECP_widgetChart = QtWidgets.QWidget(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(10)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.ECP_widgetChart.sizePolicy().hasHeightForWidth())
        self.ECP_widgetChart.setSizePolicy(sizePolicy)
        self.ECP_widgetChart.setMinimumSize(QtCore.QSize(0, 0))
        self.ECP_widgetChart.setMaximumSize(QtCore.QSize(16777215, 400))
        self.ECP_widgetChart.setObjectName("ECP_widgetChart")
        self.verticalLayout_2.addWidget(self.ECP_widgetChart)
        self.gridLayout_2.addWidget(self.frame_2, 0, 0, 1, 1)
        self.gridlayout_SD_TableWidget_4.addWidget(self.ECP_widgetReport, 0, 0, 1, 1)
        self.gridLayout_52.addWidget(self.frame_ECP_TableWidget, 0, 2, 1, 1)
        self.frame_ECP_widgetChart = QtWidgets.QFrame(self.ECP_frame_MainWindow)
        self.frame_ECP_widgetChart.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_ECP_widgetChart.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_ECP_widgetChart.setObjectName("frame_ECP_widgetChart")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame_ECP_widgetChart)
        self.gridLayout_3.setContentsMargins(-1, 22, -1, -1)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.line = QtWidgets.QFrame(self.frame_ECP_widgetChart)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_3.addWidget(self.line, 0, 0, 1, 1)
        self.line_2 = QtWidgets.QFrame(self.frame_ECP_widgetChart)
        self.line_2.setMinimumSize(QtCore.QSize(0, 10000))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout_3.addWidget(self.line_2, 0, 1, 1, 1)
        self.gridLayout_52.addWidget(self.frame_ECP_widgetChart, 0, 1, 1, 1)
        self.gridLayout.addWidget(self.ECP_frame_MainWindow, 0, 0, 1, 1)

        self.retranslateUi(unitWidget_ECP)
        QtCore.QMetaObject.connectSlotsByName(unitWidget_ECP)
        unitWidget_ECP.setTabOrder(self.ECP_CalcTarget01, self.ECP_CalcTarget02)
        unitWidget_ECP.setTabOrder(self.ECP_CalcTarget02, self.ECP_Input01)
        unitWidget_ECP.setTabOrder(self.ECP_Input01, self.ECP_Input03)
        unitWidget_ECP.setTabOrder(self.ECP_Input03, self.ECP_Input04)
        unitWidget_ECP.setTabOrder(self.ECP_Input04, self.ECP_Input05)
        unitWidget_ECP.setTabOrder(self.ECP_Input05, self.ECP_Input06)
        unitWidget_ECP.setTabOrder(self.ECP_Input06, self.ECP_Input07)
        unitWidget_ECP.setTabOrder(self.ECP_Input07, self.ECP_Input08)
        unitWidget_ECP.setTabOrder(self.ECP_Input08, self.ECP_Input09)
        unitWidget_ECP.setTabOrder(self.ECP_Input09, self.ECP_Input11)
        unitWidget_ECP.setTabOrder(self.ECP_Input11, self.ECP_Input14)
        unitWidget_ECP.setTabOrder(self.ECP_Input14, self.ECP_Input15)
        unitWidget_ECP.setTabOrder(self.ECP_Input15, self.ECP_Input16)
        unitWidget_ECP.setTabOrder(self.ECP_Input16, self.ECP_Input13)
        unitWidget_ECP.setTabOrder(self.ECP_Input13, self.ECP_save_button)
        unitWidget_ECP.setTabOrder(self.ECP_save_button, self.ECP_run_button)

    def retranslateUi(self, unitWidget_ECP):
        _translate = QtCore.QCoreApplication.translate
        unitWidget_ECP.setWindowTitle(_translate("unitWidget_ECP", "Form"))
        self.LabelSub_ECP09.setText(_translate("unitWidget_ECP", "<html><head/><body><p>Bank 4 Position<br/>(cm withdrawn)</p></body></html>"))
        self.LabelSub_ECP06.setText(_translate("unitWidget_ECP", "<html><head/><body><p>Target<br/><span style=\" font-size:10pt;\">Eigenvalue</span></p></body></html>"))
        self.ECP_Input01.setDisplayFormat(_translate("unitWidget_ECP", "yyyy-MM-dd hh:mm"))
        self.LabelSub_ECP04.setText(_translate("unitWidget_ECP", "<html><head/><body><p>Cycle Burnup<br/>(MWD/MTU)</p></body></html>"))
        self.LabelSub_ECP05.setText(_translate("unitWidget_ECP", "<html><head/><body><p>Inlet<br/>Temperature (℃)</p></body></html>"))
        self.LabelSub_ECP03.setText(_translate("unitWidget_ECP", "Core Power (%)"))
        self.ECP_Input02_Title_2.setText(_translate("unitWidget_ECP", "<html><head/><body><p>Model Setup</p></body></html>"))
        self.LabelSub_ECP01.setText(_translate("unitWidget_ECP", "<html><head/><body><p>Shutdown<br/>Date and Time</p></body></html>"))
        self.LabelSub_ECP08.setText(_translate("unitWidget_ECP", "<html><head/><body><p>Bank 5 Position<br/>(cm withdrawn)</p></body></html>"))
        self.LabelSub_ECP07.setText(_translate("unitWidget_ECP", "<html><head/><body><p>Bank P Position<br/>(cm withdrawn)</p></body></html>"))
        self.ECP_CalcTarget02.setText(_translate("unitWidget_ECP", "Rod Position Search"))
        self.ECP_CalcTarget01.setText(_translate("unitWidget_ECP", "Boron Search"))
        self.LabelTitle_ECP02.setText(_translate("unitWidget_ECP", "Calculation Type"))
        self.LabelSub_ECP15.setText(_translate("unitWidget_ECP", "<html><head/><body><p>Bank 5 Position<br/>(cm withdrawn)</p></body></html>"))
        self.LabelSub_ECP14.setText(_translate("unitWidget_ECP", "<html><head/><body><p>Bank P Position<br/>(cm withdrawn)</p></body></html>"))
        self.LabelSub_ECP16.setText(_translate("unitWidget_ECP", "<html><head/><body><p>Bank 4 Position<br/>(cm withdrawn)</p></body></html>"))
        self.ECP_Input11.setDisplayFormat(_translate("unitWidget_ECP", "yyyy-MM-dd hh:mm"))
        self.LabelSub_ECP11.setText(_translate("unitWidget_ECP", "<html><head/><body><p>Core Critiality<br/>Date and Time</span></p></body></html>"))
        self.LabelTitle_ECP06.setText(_translate("unitWidget_ECP", "<html><head/><body><p>Input Setup</p></body></html>"))
        self.LabelSub_ECP13.setText(_translate("unitWidget_ECP", "<html><head/><body><p>CBC<br/>(ppm)</span></p></body></html>"))
        self.ECP_save_button.setText(_translate("unitWidget_ECP", "Save"))
        self.ECP_run_button.setText(_translate("unitWidget_ECP", "Run"))
