# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'unitWidget_ECP_revS304.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_unitWidget_ECP(object):
    def setupUi(self, unitWidget_ECP):
        unitWidget_ECP.setObjectName("unitWidget_ECP")
        unitWidget_ECP.resize(1900, 1100)
        self.gridLayout = QtWidgets.QGridLayout(unitWidget_ECP)
        self.gridLayout.setObjectName("gridLayout")
        self.ECP_frame_MainWindow = QtWidgets.QFrame(unitWidget_ECP)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ECP_frame_MainWindow.sizePolicy().hasHeightForWidth())
        self.ECP_frame_MainWindow.setSizePolicy(sizePolicy)
        self.ECP_frame_MainWindow.setStyleSheet("background-color: rgb(44, 49, 60);\n"
"/* LINE EDIT */\n"
"QLineEdit {\n"
"    background-color: rgb(27, 29, 35);\n"
"    border-radius: 5px;\n"
"    border: 2px solid rgb(27, 29, 35);\n"
"    padding-left: 10px;\n"
"}\n"
"QLineEdit:hover {\n"
"    border: 2px solid rgb(64, 71, 88);\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 2px solid rgb(91, 101, 124);\n"
"}\n"
"\n"
"/* SCROLL BARS */\n"
"QScrollBar:horizontal {\n"
"    border: none;\n"
"    background: rgb(52, 59, 72);\n"
"    height: 14px;\n"
"    margin: 0px 21px 0 21px;\n"
"    border-radius: 0px;\n"
"}\n"
"QScrollBar::handle:horizontal {\n"
"    background: rgb(85, 170, 255);\n"
"    min-width: 25px;\n"
"    border-radius: 7px\n"
"}\n"
"QScrollBar::add-line:horizontal {\n"
"    border: none;\n"
"    background: rgb(55, 63, 77);\n"
"    width: 20px;\n"
"    border-top-right-radius: 7px;\n"
"    border-bottom-right-radius: 7px;\n"
"    subcontrol-position: right;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::sub-line:horizontal {\n"
"    border: none;\n"
"    background: rgb(55, 63, 77);\n"
"    width: 20px;\n"
"    border-top-left-radius: 7px;\n"
"    border-bottom-left-radius: 7px;\n"
"    subcontrol-position: left;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::up-arrow:horizontal, QScrollBar::down-arrow:horizontal\n"
"{\n"
"     background: none;\n"
"}\n"
"QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal\n"
"{\n"
"     background: none;\n"
"}\n"
" QScrollBar:vertical {\n"
"    border: none;\n"
"    background: rgb(52, 59, 72);\n"
"    width: 14px;\n"
"    margin: 21px 0 21px 0;\n"
"    border-radius: 0px;\n"
" }\n"
" QScrollBar::handle:vertical {    \n"
"    background: rgb(85, 170, 255);\n"
"    min-height: 25px;\n"
"    border-radius: 7px\n"
" }\n"
" QScrollBar::add-line:vertical {\n"
"     border: none;\n"
"    background: rgb(55, 63, 77);\n"
"     height: 20px;\n"
"    border-bottom-left-radius: 7px;\n"
"    border-bottom-right-radius: 7px;\n"
"     subcontrol-position: bottom;\n"
"     subcontrol-origin: margin;\n"
" }\n"
" QScrollBar::sub-line:vertical {\n"
"    border: none;\n"
"    background: rgb(55, 63, 77);\n"
"     height: 20px;\n"
"    border-top-left-radius: 7px;\n"
"    border-top-right-radius: 7px;\n"
"     subcontrol-position: top;\n"
"     subcontrol-origin: margin;\n"
" }\n"
" QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical {\n"
"     background: none;\n"
" }\n"
"\n"
" QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"     background: none;\n"
" }\n"
"\n"
"/* CHECKBOX */\n"
"QCheckBox::indicator {\n"
"    border: 3px solid rgb(52, 59, 72);\n"
"    width: 15px;\n"
"    height: 15px;\n"
"    border-radius: 10px;\n"
"    background: rgb(44, 49, 60);\n"
"}\n"
"QCheckBox::indicator:hover {\n"
"    border: 3px solid rgb(58, 66, 81);\n"
"}\n"
"QCheckBox::indicator:checked {\n"
"    background: 3px solid rgb(52, 59, 72);\n"
"    border: 3px solid rgb(52, 59, 72);    \n"
"    background-image: url(:/16x16/icons/16x16/cil-check-alt.png);\n"
"}\n"
"\n"
"/* RADIO BUTTON */\n"
"QRadioButton::indicator {\n"
"    border: 3px solid rgb(52, 59, 72);\n"
"    width: 15px;\n"
"    height: 15px;\n"
"    border-radius: 10px;\n"
"    background: rgb(44, 49, 60);\n"
"}\n"
"QRadioButton::indicator:hover {\n"
"    border: 3px solid rgb(58, 66, 81);\n"
"}\n"
"QRadioButton::indicator:checked {\n"
"    background: 3px solid rgb(94, 106, 130);\n"
"    border: 3px solid rgb(52, 59, 72);    \n"
"}\n"
"\n"
"/* COMBOBOX */\n"
"QComboBox{\n"
"    background-color: rgb(27, 29, 35);\n"
"    border-radius: 5px;\n"
"    border: 2px solid rgb(27, 29, 35);\n"
"    padding: 5px;\n"
"    padding-left: 10px;\n"
"}\n"
"QComboBox:hover{\n"
"    border: 2px solid rgb(64, 71, 88);\n"
"}\n"
"QComboBox::drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    width: 25px; \n"
"    border-left-width: 3px;\n"
"    border-left-color: rgba(39, 44, 54, 150);\n"
"    border-left-style: solid;\n"
"    border-top-right-radius: 3px;\n"
"    border-bottom-right-radius: 3px;    \n"
"    background-image: url(:/16x16/icons/16x16/cil-arrow-bottom.png);\n"
"    background-position: center;\n"
"    background-repeat: no-reperat;\n"
" }\n"
"QComboBox QAbstractItemView {\n"
"    color: rgb(85, 170, 255);    \n"
"    background-color: rgb(27, 29, 35);\n"
"    padding: 10px;\n"
"    selection-background-color: rgb(39, 44, 54);\n"
"}\n"
"\n"
"/* SLIDERS */\n"
"QSlider::groove:horizontal {\n"
"    border-radius: 9px;\n"
"    height: 18px;\n"
"    margin: 0px;\n"
"    background-color: rgb(52, 59, 72);\n"
"}\n"
"QSlider::groove:horizontal:hover {\n"
"    background-color: rgb(55, 62, 76);\n"
"}\n"
"QSlider::handle:horizontal {\n"
"    background-color: rgb(85, 170, 255);\n"
"    border: none;\n"
"    height: 18px;\n"
"    width: 18px;\n"
"    margin: 0px;\n"
"    border-radius: 9px;\n"
"}\n"
"QSlider::handle:horizontal:hover {\n"
"    background-color: rgb(105, 180, 255);\n"
"}\n"
"QSlider::handle:horizontal:pressed {\n"
"    background-color: rgb(65, 130, 195);\n"
"}\n"
"\n"
"QSlider::groove:vertical {\n"
"    border-radius: 9px;\n"
"    width: 18px;\n"
"    margin: 0px;\n"
"    background-color: rgb(52, 59, 72);\n"
"}\n"
"QSlider::groove:vertical:hover {\n"
"    background-color: rgb(55, 62, 76);\n"
"}\n"
"QSlider::handle:vertical {\n"
"    background-color: rgb(85, 170, 255);\n"
"    border: none;\n"
"    height: 18px;\n"
"    width: 18px;\n"
"    margin: 0px;\n"
"    border-radius: 9px;\n"
"}\n"
"QSlider::handle:vertical:hover {\n"
"    background-color: rgb(105, 180, 255);\n"
"}\n"
"QSlider::handle:vertical:pressed {\n"
"    background-color: rgb(65, 130, 195);\n"
"}\n"
"/* QTableWidget*/\n"
"QTableWidget {    \n"
"    background-color: rgb(38, 44, 53);\n"
"    padding: 10px;\n"
"    border-radius: 15px;\n"
"    gridline-color: rgb(44, 49, 60);\n"
"    border-bottom: 1px solid rgb(44, 49, 60);\n"
"}\n"
"QTableWidget::item{\n"
"    border-color: rgb(44, 49, 60);\n"
"    padding-left: 5px;\n"
"    padding-right: 5px;\n"
"    gridline-color: rgb(44, 49, 60);\n"
"}\n"
"QTableWidget::item:selected{\n"
"    background-color: rgb(85, 170, 255);\n"
"}\n"
"QScrollBar:horizontal {\n"
"    border: none;\n"
"    background: rgb(52, 59, 72);\n"
"    height: 14px;\n"
"    margin: 0px 21px 0 21px;\n"
"    border-radius: 0px;\n"
"}\n"
"\n"
"QScrollBar:handle:horizontal {\n"
"    background: rgb(91, 101, 124);\n"
"\n"
"}\n"
"\n"
" QScrollBar:vertical {\n"
"    border: none;\n"
"    background: rgb(52, 59, 72);\n"
"    width: 14px;\n"
"    margin: 21px 0 21px 0;\n"
"    border-radius: 0px;\n"
" }\n"
"QHeaderView::section{\n"
"    Background-color: rgb(39, 44, 54);\n"
"    max-width: 30px;\n"
"    border: 1px solid rgb(44, 49, 60);\n"
"    border-style: none;\n"
"    border-bottom: 1px solid rgb(44, 49, 60);\n"
"    border-right: 1px solid rgb(44, 49, 60);\n"
"}\n"
"QTableWidget::horizontalHeader {    \n"
"    background-color: rgb(190, 190, 190);\n"
"}\n"
"\n"
"QHeaderView::section:horizontal\n"
"{\n"
"    background-color: rgb(51, 59, 70);\n"
"    padding: 3px;\n"
"    border-top-left-radius: 7px;\n"
"    border-top-right-radius: 7px;\n"
"    color: rgb(167,    174, 183);\n"
"}\n"
"QHeaderView::section:vertical\n"
"{\n"
"    border: 1px solid rgb(44, 49, 60);\n"
"}\n"
"\n"
"QScrollBar:handle:vertical {\n"
"    background: rgb(91, 101, 124);\n"
"\n"
"}\n"
"\n"
"QTableCornerButton::section{ \n"
"\n"
"    background-color: rgb(38, 44, 53);\n"
"}\n"
"\n"
"")
        self.ECP_frame_MainWindow.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.ECP_frame_MainWindow.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ECP_frame_MainWindow.setObjectName("ECP_frame_MainWindow")
        self.gridLayout_52 = QtWidgets.QGridLayout(self.ECP_frame_MainWindow)
        self.gridLayout_52.setContentsMargins(9, 9, 9, 9)
        self.gridLayout_52.setSpacing(7)
        self.gridLayout_52.setObjectName("gridLayout_52")
        self.frame_ECP_OutputWidget = QtWidgets.QFrame(self.ECP_frame_MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(200)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_ECP_OutputWidget.sizePolicy().hasHeightForWidth())
        self.frame_ECP_OutputWidget.setSizePolicy(sizePolicy)
        self.frame_ECP_OutputWidget.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_ECP_OutputWidget.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_ECP_OutputWidget.setObjectName("frame_ECP_OutputWidget")
        self.gridlayout_SD_Dummy = QtWidgets.QGridLayout(self.frame_ECP_OutputWidget)
        self.gridlayout_SD_Dummy.setContentsMargins(0, 0, 0, 0)
        self.gridlayout_SD_Dummy.setSpacing(0)
        self.gridlayout_SD_Dummy.setObjectName("gridlayout_SD_Dummy")
        self.gridlayout_ECP_TableWidget = QtWidgets.QGridLayout()
        self.gridlayout_ECP_TableWidget.setSpacing(0)
        self.gridlayout_ECP_TableWidget.setObjectName("gridlayout_ECP_TableWidget")
        self.ECP_frameChart = QtWidgets.QFrame(self.frame_ECP_OutputWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(10)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.ECP_frameChart.sizePolicy().hasHeightForWidth())
        self.ECP_frameChart.setSizePolicy(sizePolicy)
        self.ECP_frameChart.setMinimumSize(QtCore.QSize(0, 0))
        self.ECP_frameChart.setStyleSheet("QFrame { \n"
"   border-left:  1px solid rgb(90,90,90);\n"
"/*  border-right:  1px solid rgb(90,90,90);\n"
"   border-bottom:  1px solid rgb(90,90,90); */\n"
"   border-top:  1px solid rgb(90,90,90);\n"
"}")
        self.ECP_frameChart.setFrameShape(QtWidgets.QFrame.Box)
        self.ECP_frameChart.setObjectName("ECP_frameChart")
        self.grid_ECP_frameChart_DUMMY = QtWidgets.QGridLayout(self.ECP_frameChart)
        self.grid_ECP_frameChart_DUMMY.setContentsMargins(0, 0, 0, 0)
        self.grid_ECP_frameChart_DUMMY.setSpacing(0)
        self.grid_ECP_frameChart_DUMMY.setObjectName("grid_ECP_frameChart_DUMMY")
        self.grid_ECP_frameChart = QtWidgets.QGridLayout()
        self.grid_ECP_frameChart.setSpacing(0)
        self.grid_ECP_frameChart.setObjectName("grid_ECP_frameChart")
        self.grid_ECP_frameChart_DUMMY.addLayout(self.grid_ECP_frameChart, 0, 0, 1, 1)
        self.gridlayout_ECP_TableWidget.addWidget(self.ECP_frameChart, 0, 0, 1, 1)
        self.ECP_frameChart02 = QtWidgets.QFrame(self.frame_ECP_OutputWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(10)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.ECP_frameChart02.sizePolicy().hasHeightForWidth())
        self.ECP_frameChart02.setSizePolicy(sizePolicy)
        self.ECP_frameChart02.setMinimumSize(QtCore.QSize(0, 0))
        self.ECP_frameChart02.setStyleSheet("QFrame { \n"
"   border-left:  1px solid rgb(90,90,90);\n"
"/*  border-right:  1px solid rgb(90,90,90);*/\n"
"   border-bottom:  1px solid rgb(90,90,90);\n"
"   border-top:  1px solid rgb(90,90,90);\n"
"}")
        self.ECP_frameChart02.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.ECP_frameChart02.setMidLineWidth(0)
        self.ECP_frameChart02.setObjectName("ECP_frameChart02")
        self.grid_ECP_frameChart_DUMMY02 = QtWidgets.QGridLayout(self.ECP_frameChart02)
        self.grid_ECP_frameChart_DUMMY02.setContentsMargins(0, 0, 0, 0)
        self.grid_ECP_frameChart_DUMMY02.setSpacing(0)
        self.grid_ECP_frameChart_DUMMY02.setObjectName("grid_ECP_frameChart_DUMMY02")
        self.grid_ECP_frameChart02 = QtWidgets.QGridLayout()
        self.grid_ECP_frameChart02.setSpacing(0)
        self.grid_ECP_frameChart02.setObjectName("grid_ECP_frameChart02")
        self.grid_ECP_frameChart_DUMMY02.addLayout(self.grid_ECP_frameChart02, 0, 0, 1, 1)
        self.gridlayout_ECP_TableWidget.addWidget(self.ECP_frameChart02, 1, 0, 1, 1)
        self.ECP_InputLP_Dframe = QtWidgets.QFrame(self.frame_ECP_OutputWidget)
        self.ECP_InputLP_Dframe.setStyleSheet("QFrame { \n"
"   border-left:  1px solid rgb(90,90,90);\n"
"   border-right:  1px solid rgb(90,90,90);\n"
"   border-bottom:  1px solid rgb(90,90,90);\n"
"   border-top:  1px solid rgb(90,90,90);\n"
"}\n"
"")
        self.ECP_InputLP_Dframe.setFrameShape(QtWidgets.QFrame.Box)
        self.ECP_InputLP_Dframe.setFrameShadow(QtWidgets.QFrame.Plain)
        self.ECP_InputLP_Dframe.setObjectName("ECP_InputLP_Dframe")
        self.gridLayout_ECP_InputLP_Dframe = QtWidgets.QGridLayout(self.ECP_InputLP_Dframe)
        self.gridLayout_ECP_InputLP_Dframe.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_ECP_InputLP_Dframe.setSpacing(0)
        self.gridLayout_ECP_InputLP_Dframe.setObjectName("gridLayout_ECP_InputLP_Dframe")
#         self.ECP_InputLP_frame = QtWidgets.QFrame(self.ECP_InputLP_Dframe)
#         sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
#         sizePolicy.setHorizontalStretch(0)
#         sizePolicy.setVerticalStretch(0)
#         sizePolicy.setHeightForWidth(self.ECP_InputLP_frame.sizePolicy().hasHeightForWidth())
#         self.ECP_InputLP_frame.setSizePolicy(sizePolicy)
#         self.ECP_InputLP_frame.setMinimumSize(QtCore.QSize(0, 0))
#         self.ECP_InputLP_frame.setMaximumSize(QtCore.QSize(16777215, 16777215))
#         self.ECP_InputLP_frame.setSizeIncrement(QtCore.QSize(0, 0))
#         self.ECP_InputLP_frame.setBaseSize(QtCore.QSize(0, 0))
#         self.ECP_InputLP_frame.setStyleSheet("QFrame { \n"
# "   border: 0px solid rgb(90,90,90);\n"
# "\n"
# "\n"
# "}\n"
# "")
#         self.ECP_InputLP_frame.setFrameShape(QtWidgets.QFrame.NoFrame)
#         self.ECP_InputLP_frame.setFrameShadow(QtWidgets.QFrame.Plain)
#         self.ECP_InputLP_frame.setLineWidth(0)
#         self.ECP_InputLP_frame.setObjectName("ECP_InputLP_frame")
#         self.ECP_InputLPgrid = QtWidgets.QGridLayout(self.ECP_InputLP_frame)
#         self.ECP_InputLPgrid.setContentsMargins(3, 3, 3, 3)
#         self.ECP_InputLPgrid.setSpacing(0)
#         self.ECP_InputLPgrid.setObjectName("ECP_InputLPgrid")
#         self.labelY_12Y = QtWidgets.QLabel(self.ECP_InputLP_frame)
#         sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
#         sizePolicy.setHorizontalStretch(0)
#         sizePolicy.setVerticalStretch(10)
#         sizePolicy.setHeightForWidth(self.labelY_12Y.sizePolicy().hasHeightForWidth())
#         self.labelY_12Y.setSizePolicy(sizePolicy)
#         self.labelY_12Y.setMinimumSize(QtCore.QSize(25, 15))
#         self.labelY_12Y.setMaximumSize(QtCore.QSize(35, 16777215))
#         font = QtGui.QFont()
#         font.setPointSize(12)
#         self.labelY_12Y.setFont(font)
#         self.labelY_12Y.setAlignment(QtCore.Qt.AlignCenter)
#         self.labelY_12Y.setObjectName("labelY_12Y")
#         self.ECP_InputLPgrid.addWidget(self.labelY_12Y, 5, 0, 1, 1)
#         self.labelY_11Y = QtWidgets.QLabel(self.ECP_InputLP_frame)
#         sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
#         sizePolicy.setHorizontalStretch(0)
#         sizePolicy.setVerticalStretch(10)
#         sizePolicy.setHeightForWidth(self.labelY_11Y.sizePolicy().hasHeightForWidth())
#         self.labelY_11Y.setSizePolicy(sizePolicy)
#         self.labelY_11Y.setMinimumSize(QtCore.QSize(25, 15))
#         self.labelY_11Y.setMaximumSize(QtCore.QSize(35, 16777215))
#         font = QtGui.QFont()
#         font.setPointSize(12)
#         self.labelY_11Y.setFont(font)
#         self.labelY_11Y.setAlignment(QtCore.Qt.AlignCenter)
#         self.labelY_11Y.setObjectName("labelY_11Y")
#         self.ECP_InputLPgrid.addWidget(self.labelY_11Y, 4, 0, 1, 1)
#         self.labelX_J = QtWidgets.QLabel(self.ECP_InputLP_frame)
#         sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
#         sizePolicy.setHorizontalStretch(10)
#         sizePolicy.setVerticalStretch(0)
#         sizePolicy.setHeightForWidth(self.labelX_J.sizePolicy().hasHeightForWidth())
#         self.labelX_J.setSizePolicy(sizePolicy)
#         self.labelX_J.setMinimumSize(QtCore.QSize(15, 25))
#         self.labelX_J.setMaximumSize(QtCore.QSize(16777215, 25))
#         font = QtGui.QFont()
#         font.setPointSize(12)
#         self.labelX_J.setFont(font)
#         self.labelX_J.setAlignment(QtCore.Qt.AlignCenter)
#         self.labelX_J.setObjectName("labelX_J")
#         self.ECP_InputLPgrid.addWidget(self.labelX_J, 0, 2, 1, 1)
#         self.labelX_L = QtWidgets.QLabel(self.ECP_InputLP_frame)
#         sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
#         sizePolicy.setHorizontalStretch(10)
#         sizePolicy.setVerticalStretch(0)
#         sizePolicy.setHeightForWidth(self.labelX_L.sizePolicy().hasHeightForWidth())
#         self.labelX_L.setSizePolicy(sizePolicy)
#         self.labelX_L.setMinimumSize(QtCore.QSize(15, 25))
#         self.labelX_L.setMaximumSize(QtCore.QSize(16777215, 25))
#         font = QtGui.QFont()
#         font.setPointSize(12)
#         self.labelX_L.setFont(font)
#         self.labelX_L.setAlignment(QtCore.Qt.AlignCenter)
#         self.labelX_L.setObjectName("labelX_L")
#         self.ECP_InputLPgrid.addWidget(self.labelX_L, 0, 4, 1, 1)
#         self.labelY_09Y = QtWidgets.QLabel(self.ECP_InputLP_frame)
#         sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
#         sizePolicy.setHorizontalStretch(0)
#         sizePolicy.setVerticalStretch(10)
#         sizePolicy.setHeightForWidth(self.labelY_09Y.sizePolicy().hasHeightForWidth())
#         self.labelY_09Y.setSizePolicy(sizePolicy)
#         self.labelY_09Y.setMinimumSize(QtCore.QSize(25, 15))
#         self.labelY_09Y.setMaximumSize(QtCore.QSize(35, 16777215))
#         font = QtGui.QFont()
#         font.setPointSize(12)
#         self.labelY_09Y.setFont(font)
#         self.labelY_09Y.setAlignment(QtCore.Qt.AlignCenter)
#         self.labelY_09Y.setObjectName("labelY_09Y")
#         self.ECP_InputLPgrid.addWidget(self.labelY_09Y, 2, 0, 1, 1)
#         self.labelY_08Y = QtWidgets.QLabel(self.ECP_InputLP_frame)
#         sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
#         sizePolicy.setHorizontalStretch(0)
#         sizePolicy.setVerticalStretch(10)
#         sizePolicy.setHeightForWidth(self.labelY_08Y.sizePolicy().hasHeightForWidth())
#         self.labelY_08Y.setSizePolicy(sizePolicy)
#         self.labelY_08Y.setMinimumSize(QtCore.QSize(25, 15))
#         self.labelY_08Y.setMaximumSize(QtCore.QSize(35, 16777215))
#         font = QtGui.QFont()
#         font.setPointSize(12)
#         self.labelY_08Y.setFont(font)
#         self.labelY_08Y.setAlignment(QtCore.Qt.AlignCenter)
#         self.labelY_08Y.setObjectName("labelY_08Y")
#         self.ECP_InputLPgrid.addWidget(self.labelY_08Y, 1, 0, 1, 1)
#         self.labelX_R = QtWidgets.QLabel(self.ECP_InputLP_frame)
#         sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
#         sizePolicy.setHorizontalStretch(10)
#         sizePolicy.setVerticalStretch(0)
#         sizePolicy.setHeightForWidth(self.labelX_R.sizePolicy().hasHeightForWidth())
#         self.labelX_R.setSizePolicy(sizePolicy)
#         self.labelX_R.setMinimumSize(QtCore.QSize(15, 25))
#         self.labelX_R.setMaximumSize(QtCore.QSize(16777215, 25))
#         font = QtGui.QFont()
#         font.setPointSize(12)
#         self.labelX_R.setFont(font)
#         self.labelX_R.setAlignment(QtCore.Qt.AlignCenter)
#         self.labelX_R.setObjectName("labelX_R")
#         self.ECP_InputLPgrid.addWidget(self.labelX_R, 0, 8, 1, 1)
#         self.labelY_15Y = QtWidgets.QLabel(self.ECP_InputLP_frame)
#         sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
#         sizePolicy.setHorizontalStretch(0)
#         sizePolicy.setVerticalStretch(10)
#         sizePolicy.setHeightForWidth(self.labelY_15Y.sizePolicy().hasHeightForWidth())
#         self.labelY_15Y.setSizePolicy(sizePolicy)
#         self.labelY_15Y.setMinimumSize(QtCore.QSize(25, 15))
#         self.labelY_15Y.setMaximumSize(QtCore.QSize(35, 16777215))
#         font = QtGui.QFont()
#         font.setPointSize(12)
#         self.labelY_15Y.setFont(font)
#         self.labelY_15Y.setAlignment(QtCore.Qt.AlignCenter)
#         self.labelY_15Y.setObjectName("labelY_15Y")
#         self.ECP_InputLPgrid.addWidget(self.labelY_15Y, 8, 0, 1, 1)
#         self.labelX_M = QtWidgets.QLabel(self.ECP_InputLP_frame)
#         sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
#         sizePolicy.setHorizontalStretch(10)
#         sizePolicy.setVerticalStretch(0)
#         sizePolicy.setHeightForWidth(self.labelX_M.sizePolicy().hasHeightForWidth())
#         self.labelX_M.setSizePolicy(sizePolicy)
#         self.labelX_M.setMinimumSize(QtCore.QSize(15, 25))
#         self.labelX_M.setMaximumSize(QtCore.QSize(16777215, 25))
#         font = QtGui.QFont()
#         font.setPointSize(12)
#         self.labelX_M.setFont(font)
#         self.labelX_M.setAlignment(QtCore.Qt.AlignCenter)
#         self.labelX_M.setObjectName("labelX_M")
#         self.ECP_InputLPgrid.addWidget(self.labelX_M, 0, 5, 1, 1)
#         self.labelX_H = QtWidgets.QLabel(self.ECP_InputLP_frame)
#         sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
#         sizePolicy.setHorizontalStretch(10)
#         sizePolicy.setVerticalStretch(0)
#         sizePolicy.setHeightForWidth(self.labelX_H.sizePolicy().hasHeightForWidth())
#         self.labelX_H.setSizePolicy(sizePolicy)
#         self.labelX_H.setMinimumSize(QtCore.QSize(15, 25))
#         self.labelX_H.setMaximumSize(QtCore.QSize(16777215, 25))
#         font = QtGui.QFont()
#         font.setPointSize(12)
#         self.labelX_H.setFont(font)
#         self.labelX_H.setAlignment(QtCore.Qt.AlignCenter)
#         self.labelX_H.setObjectName("labelX_H")
#         self.ECP_InputLPgrid.addWidget(self.labelX_H, 0, 1, 1, 1)
#         self.labelX_P = QtWidgets.QLabel(self.ECP_InputLP_frame)
#         sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
#         sizePolicy.setHorizontalStretch(10)
#         sizePolicy.setVerticalStretch(0)
#         sizePolicy.setHeightForWidth(self.labelX_P.sizePolicy().hasHeightForWidth())
#         self.labelX_P.setSizePolicy(sizePolicy)
#         self.labelX_P.setMinimumSize(QtCore.QSize(15, 25))
#         self.labelX_P.setMaximumSize(QtCore.QSize(16777215, 25))
#         font = QtGui.QFont()
#         font.setPointSize(12)
#         self.labelX_P.setFont(font)
#         self.labelX_P.setAlignment(QtCore.Qt.AlignCenter)
#         self.labelX_P.setObjectName("labelX_P")
#         self.ECP_InputLPgrid.addWidget(self.labelX_P, 0, 7, 1, 1)
#         self.labelX_K = QtWidgets.QLabel(self.ECP_InputLP_frame)
#         sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
#         sizePolicy.setHorizontalStretch(10)
#         sizePolicy.setVerticalStretch(0)
#         sizePolicy.setHeightForWidth(self.labelX_K.sizePolicy().hasHeightForWidth())
#         self.labelX_K.setSizePolicy(sizePolicy)
#         self.labelX_K.setMinimumSize(QtCore.QSize(15, 25))
#         self.labelX_K.setMaximumSize(QtCore.QSize(16777215, 25))
#         font = QtGui.QFont()
#         font.setPointSize(12)
#         self.labelX_K.setFont(font)
#         self.labelX_K.setAlignment(QtCore.Qt.AlignCenter)
#         self.labelX_K.setObjectName("labelX_K")
#         self.ECP_InputLPgrid.addWidget(self.labelX_K, 0, 3, 1, 1)
#         self.labelY_14Y = QtWidgets.QLabel(self.ECP_InputLP_frame)
#         sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
#         sizePolicy.setHorizontalStretch(0)
#         sizePolicy.setVerticalStretch(10)
#         sizePolicy.setHeightForWidth(self.labelY_14Y.sizePolicy().hasHeightForWidth())
#         self.labelY_14Y.setSizePolicy(sizePolicy)
#         self.labelY_14Y.setMinimumSize(QtCore.QSize(25, 15))
#         self.labelY_14Y.setMaximumSize(QtCore.QSize(35, 16777215))
#         font = QtGui.QFont()
#         font.setPointSize(12)
#         self.labelY_14Y.setFont(font)
#         self.labelY_14Y.setAlignment(QtCore.Qt.AlignCenter)
#         self.labelY_14Y.setObjectName("labelY_14Y")
#         self.ECP_InputLPgrid.addWidget(self.labelY_14Y, 7, 0, 1, 1)
#         self.labelY_10Y = QtWidgets.QLabel(self.ECP_InputLP_frame)
#         sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
#         sizePolicy.setHorizontalStretch(0)
#         sizePolicy.setVerticalStretch(10)
#         sizePolicy.setHeightForWidth(self.labelY_10Y.sizePolicy().hasHeightForWidth())
#         self.labelY_10Y.setSizePolicy(sizePolicy)
#         self.labelY_10Y.setMinimumSize(QtCore.QSize(25, 15))
#         self.labelY_10Y.setMaximumSize(QtCore.QSize(35, 16777215))
#         font = QtGui.QFont()
#         font.setPointSize(12)
#         self.labelY_10Y.setFont(font)
#         self.labelY_10Y.setAlignment(QtCore.Qt.AlignCenter)
#         self.labelY_10Y.setObjectName("labelY_10Y")
#         self.ECP_InputLPgrid.addWidget(self.labelY_10Y, 3, 0, 1, 1)
#         self.labelY_13Y = QtWidgets.QLabel(self.ECP_InputLP_frame)
#         sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
#         sizePolicy.setHorizontalStretch(0)
#         sizePolicy.setVerticalStretch(10)
#         sizePolicy.setHeightForWidth(self.labelY_13Y.sizePolicy().hasHeightForWidth())
#         self.labelY_13Y.setSizePolicy(sizePolicy)
#         self.labelY_13Y.setMinimumSize(QtCore.QSize(25, 15))
#         self.labelY_13Y.setMaximumSize(QtCore.QSize(35, 16777215))
#         font = QtGui.QFont()
#         font.setPointSize(12)
#         self.labelY_13Y.setFont(font)
#         self.labelY_13Y.setAlignment(QtCore.Qt.AlignCenter)
#         self.labelY_13Y.setObjectName("labelY_13Y")
#         self.ECP_InputLPgrid.addWidget(self.labelY_13Y, 6, 0, 1, 1)
#         self.labelX_N = QtWidgets.QLabel(self.ECP_InputLP_frame)
#         sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
#         sizePolicy.setHorizontalStretch(10)
#         sizePolicy.setVerticalStretch(0)
#         sizePolicy.setHeightForWidth(self.labelX_N.sizePolicy().hasHeightForWidth())
#         self.labelX_N.setSizePolicy(sizePolicy)
#         self.labelX_N.setMinimumSize(QtCore.QSize(15, 25))
#         self.labelX_N.setMaximumSize(QtCore.QSize(16777215, 25))
#         font = QtGui.QFont()
#         font.setPointSize(12)
#         self.labelX_N.setFont(font)
#         self.labelX_N.setAlignment(QtCore.Qt.AlignCenter)
#         self.labelX_N.setObjectName("labelX_N")
#         self.ECP_InputLPgrid.addWidget(self.labelX_N, 0, 6, 1, 1)
#         self.gridLayout_ECP_InputLP_Dframe.addWidget(self.ECP_InputLP_frame, 0, 0, 1, 1)
        self.gridlayout_ECP_TableWidget.addWidget(self.ECP_InputLP_Dframe, 1, 1, 1, 1)
        self.ECP_frameAxialDummy = QtWidgets.QFrame(self.frame_ECP_OutputWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(5)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.ECP_frameAxialDummy.sizePolicy().hasHeightForWidth())
        self.ECP_frameAxialDummy.setSizePolicy(sizePolicy)
        self.ECP_frameAxialDummy.setStyleSheet("QFrame { \n"
"   border-left:  1px solid rgb(90,90,90);\n"
"   border-right:  1px solid rgb(90,90,90);\n"
"/*   border-bottom:  1px solid rgb(90,90,90);*/\n"
"   border-top:  1px solid rgb(90,90,90);\n"
"}")
        self.ECP_frameAxialDummy.setFrameShape(QtWidgets.QFrame.Box)
        self.ECP_frameAxialDummy.setFrameShadow(QtWidgets.QFrame.Plain)
        self.ECP_frameAxialDummy.setObjectName("ECP_frameAxialDummy")
        self.gridLayout_AxialDummy = QtWidgets.QGridLayout(self.ECP_frameAxialDummy)
        self.gridLayout_AxialDummy.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_AxialDummy.setSpacing(0)
        self.gridLayout_AxialDummy.setObjectName("gridLayout_AxialDummy")
        self.ECP_WidgetAxial = QtWidgets.QWidget(self.ECP_frameAxialDummy)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(6)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.ECP_WidgetAxial.sizePolicy().hasHeightForWidth())
        self.ECP_WidgetAxial.setSizePolicy(sizePolicy)
        self.ECP_WidgetAxial.setMinimumSize(QtCore.QSize(0, 0))
        self.ECP_WidgetAxial.setObjectName("ECP_WidgetAxial")
        self.gridLayout_AxialDummy.addWidget(self.ECP_WidgetAxial, 0, 0, 1, 1)
        self.gridlayout_ECP_TableWidget.addWidget(self.ECP_frameAxialDummy, 0, 1, 1, 1)
        self.gridlayout_SD_Dummy.addLayout(self.gridlayout_ECP_TableWidget, 0, 0, 1, 1)
        self.gridLayout_52.addWidget(self.frame_ECP_OutputWidget, 0, 1, 1, 1)
        self.ECP_frame_InputSet = QtWidgets.QFrame(self.ECP_frame_MainWindow)
        self.ECP_frame_InputSet.setMinimumSize(QtCore.QSize(300, 0))
        self.ECP_frame_InputSet.setMaximumSize(QtCore.QSize(300, 16777215))
        self.ECP_frame_InputSet.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.ECP_frame_InputSet.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ECP_frame_InputSet.setObjectName("ECP_frame_InputSet")
        self.gridLayout_ECP_DUMMY = QtWidgets.QGridLayout(self.ECP_frame_InputSet)
        self.gridLayout_ECP_DUMMY.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_ECP_DUMMY.setSpacing(0)
        self.gridLayout_ECP_DUMMY.setObjectName("gridLayout_ECP_DUMMY")
        self.gridLayout_ECPTotal = QtWidgets.QGridLayout()
        self.gridLayout_ECPTotal.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_ECPTotal.setHorizontalSpacing(6)
        self.gridLayout_ECPTotal.setVerticalSpacing(20)
        self.gridLayout_ECPTotal.setObjectName("gridLayout_ECPTotal")
        self.gridLayout_ECP_I01 = QtWidgets.QGridLayout()
        self.gridLayout_ECP_I01.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_ECP_I01.setHorizontalSpacing(6)
        self.gridLayout_ECP_I01.setVerticalSpacing(20)
        self.gridLayout_ECP_I01.setObjectName("gridLayout_ECP_I01")
        self.LabelSub_Selete00 = QtWidgets.QLabel(self.ECP_frame_InputSet)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LabelSub_Selete00.sizePolicy().hasHeightForWidth())
        self.LabelSub_Selete00.setSizePolicy(sizePolicy)
        self.LabelSub_Selete00.setMinimumSize(QtCore.QSize(120, 0))
        self.LabelSub_Selete00.setMaximumSize(QtCore.QSize(120, 16777215))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.LabelSub_Selete00.setFont(font)
        self.LabelSub_Selete00.setObjectName("LabelSub_Selete00")
        self.gridLayout_ECP_I01.addWidget(self.LabelSub_Selete00, 1, 1, 1, 1)
        self.LabelSub_ECP00 = QtWidgets.QLabel(self.ECP_frame_InputSet)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LabelSub_ECP00.sizePolicy().hasHeightForWidth())
        self.LabelSub_ECP00.setSizePolicy(sizePolicy)
        self.LabelSub_ECP00.setMinimumSize(QtCore.QSize(120, 0))
        self.LabelSub_ECP00.setMaximumSize(QtCore.QSize(120, 16777215))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.LabelSub_ECP00.setFont(font)
        self.LabelSub_ECP00.setObjectName("LabelSub_ECP00")
        self.gridLayout_ECP_I01.addWidget(self.LabelSub_ECP00, 3, 1, 1, 1)
        self.LabelSub_ECP03 = QtWidgets.QLabel(self.ECP_frame_InputSet)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LabelSub_ECP03.sizePolicy().hasHeightForWidth())
        self.LabelSub_ECP03.setSizePolicy(sizePolicy)
        self.LabelSub_ECP03.setMinimumSize(QtCore.QSize(120, 0))
        self.LabelSub_ECP03.setMaximumSize(QtCore.QSize(120, 16777215))
        self.LabelSub_ECP03.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.LabelSub_ECP03.setFont(font)
        self.LabelSub_ECP03.setObjectName("LabelSub_ECP03")
        self.gridLayout_ECP_I01.addWidget(self.LabelSub_ECP03, 5, 1, 1, 1)
        self.LabelSub_ECP15 = QtWidgets.QLabel(self.ECP_frame_InputSet)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LabelSub_ECP15.sizePolicy().hasHeightForWidth())
        self.LabelSub_ECP15.setSizePolicy(sizePolicy)
        self.LabelSub_ECP15.setMinimumSize(QtCore.QSize(120, 0))
        self.LabelSub_ECP15.setMaximumSize(QtCore.QSize(120, 16777215))
        self.LabelSub_ECP15.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.LabelSub_ECP15.setFont(font)
        self.LabelSub_ECP15.setObjectName("LabelSub_ECP15")
        self.gridLayout_ECP_I01.addWidget(self.LabelSub_ECP15, 9, 1, 1, 1)
        self.ECP_Input00 = QtWidgets.QComboBox(self.ECP_frame_InputSet)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ECP_Input00.sizePolicy().hasHeightForWidth())
        self.ECP_Input00.setSizePolicy(sizePolicy)
        self.ECP_Input00.setMinimumSize(QtCore.QSize(120, 0))
        self.ECP_Input00.setMaximumSize(QtCore.QSize(120, 16777215))
        self.ECP_Input00.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.ECP_Input00.setFont(font)
        self.ECP_Input00.setObjectName("ECP_Input00")
        self.ECP_Input00.addItem("")
        self.ECP_Input00.addItem("")
        self.gridLayout_ECP_I01.addWidget(self.ECP_Input00, 3, 3, 1, 1)
        self.gridLayout_ECP03_I05 = QtWidgets.QGridLayout()
        self.gridLayout_ECP03_I05.setSpacing(0)
        self.gridLayout_ECP03_I05.setObjectName("gridLayout_ECP03_I05")
        spacerItem = QtWidgets.QSpacerItem(1, 1, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_ECP03_I05.addItem(spacerItem, 2, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(1, 1, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_ECP03_I05.addItem(spacerItem1, 0, 0, 1, 1)
        self.ECP_Input15 = QtWidgets.QDoubleSpinBox(self.ECP_frame_InputSet)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ECP_Input15.sizePolicy().hasHeightForWidth())
        self.ECP_Input15.setSizePolicy(sizePolicy)
        self.ECP_Input15.setMinimumSize(QtCore.QSize(120, 0))
        self.ECP_Input15.setMaximumSize(QtCore.QSize(120, 16777215))
        self.ECP_Input15.setSizeIncrement(QtCore.QSize(0, 0))
        self.ECP_Input15.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        self.ECP_Input15.setFont(font)
        self.ECP_Input15.setStyleSheet("padding: 3px;")
        self.ECP_Input15.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.ECP_Input15.setProperty("showGroupSeparator", True)
        self.ECP_Input15.setMaximum(1000.0)
        self.ECP_Input15.setStepType(QtWidgets.QAbstractSpinBox.DefaultStepType)
        self.ECP_Input15.setProperty("value", 381.0)
        self.ECP_Input15.setObjectName("ECP_Input15")
        self.gridLayout_ECP03_I05.addWidget(self.ECP_Input15, 1, 0, 1, 1)
        self.gridLayout_ECP_I01.addLayout(self.gridLayout_ECP03_I05, 9, 3, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(10000, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_ECP_I01.addItem(spacerItem2, 1, 2, 10, 1)
        self.horizontalLayout_ECP_I01T = QtWidgets.QHBoxLayout()
        self.horizontalLayout_ECP_I01T.setObjectName("horizontalLayout_ECP_I01T")
        self.LabelTitle_ECP01 = QtWidgets.QLabel(self.ECP_frame_InputSet)
        self.LabelTitle_ECP01.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.LabelTitle_ECP01.setFont(font)
        self.LabelTitle_ECP01.setObjectName("LabelTitle_ECP01")
        self.horizontalLayout_ECP_I01T.addWidget(self.LabelTitle_ECP01)
        spacerItem3 = QtWidgets.QSpacerItem(1, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_ECP_I01T.addItem(spacerItem3)
        self.gridLayout_ECP_I01.addLayout(self.horizontalLayout_ECP_I01T, 0, 0, 1, 4)
        self.gridLayout_ECP03_I01 = QtWidgets.QGridLayout()
        self.gridLayout_ECP03_I01.setSpacing(0)
        self.gridLayout_ECP03_I01.setObjectName("gridLayout_ECP03_I01")
        spacerItem4 = QtWidgets.QSpacerItem(1, 1, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_ECP03_I01.addItem(spacerItem4, 0, 0, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(1, 1, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_ECP03_I01.addItem(spacerItem5, 2, 0, 1, 1)
        self.ECP_Input12 = QtWidgets.QDoubleSpinBox(self.ECP_frame_InputSet)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ECP_Input12.sizePolicy().hasHeightForWidth())
        self.ECP_Input12.setSizePolicy(sizePolicy)
        self.ECP_Input12.setMinimumSize(QtCore.QSize(120, 0))
        self.ECP_Input12.setMaximumSize(QtCore.QSize(120, 16777215))
        self.ECP_Input12.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.ECP_Input12.setFont(font)
        self.ECP_Input12.setStyleSheet("padding: 3px;")
        self.ECP_Input12.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.ECP_Input12.setProperty("showGroupSeparator", True)
        self.ECP_Input12.setMinimum(1.0)
        self.ECP_Input12.setMaximum(1000.0)
        self.ECP_Input12.setStepType(QtWidgets.QAbstractSpinBox.DefaultStepType)
        self.ECP_Input12.setProperty("value", 30.0)
        self.ECP_Input12.setObjectName("ECP_Input12")
        self.gridLayout_ECP03_I01.addWidget(self.ECP_Input12, 1, 0, 1, 1)
        self.gridLayout_ECP_I01.addLayout(self.gridLayout_ECP03_I01, 6, 3, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(5, 5, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_ECP_I01.addItem(spacerItem6, 1, 0, 10, 1)
        self.gridLayout_ECP03_I03 = QtWidgets.QGridLayout()
        self.gridLayout_ECP03_I03.setSpacing(0)
        self.gridLayout_ECP03_I03.setObjectName("gridLayout_ECP03_I03")
        spacerItem7 = QtWidgets.QSpacerItem(1, 1, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_ECP03_I03.addItem(spacerItem7, 2, 0, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(1, 1, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_ECP03_I03.addItem(spacerItem8, 0, 0, 1, 1)
        self.ECP_Input13 = QtWidgets.QDoubleSpinBox(self.ECP_frame_InputSet)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ECP_Input13.sizePolicy().hasHeightForWidth())
        self.ECP_Input13.setSizePolicy(sizePolicy)
        self.ECP_Input13.setMinimumSize(QtCore.QSize(120, 0))
        self.ECP_Input13.setMaximumSize(QtCore.QSize(120, 16777215))
        self.ECP_Input13.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.ECP_Input13.setFont(font)
        self.ECP_Input13.setStyleSheet("padding: 3px;")
        self.ECP_Input13.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.ECP_Input13.setProperty("showGroupSeparator", True)
        self.ECP_Input13.setMaximum(10000.0)
        self.ECP_Input13.setStepType(QtWidgets.QAbstractSpinBox.DefaultStepType)
        self.ECP_Input13.setProperty("value", 0.0)
        self.ECP_Input13.setObjectName("ECP_Input13")
        self.gridLayout_ECP03_I03.addWidget(self.ECP_Input13, 1, 0, 1, 1)
        self.gridLayout_ECP_I01.addLayout(self.gridLayout_ECP03_I03, 7, 3, 1, 1)
        self.gridLayout_ECP03_I06 = QtWidgets.QGridLayout()
        self.gridLayout_ECP03_I06.setSpacing(0)
        self.gridLayout_ECP03_I06.setObjectName("gridLayout_ECP03_I06")
        spacerItem9 = QtWidgets.QSpacerItem(1, 1, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_ECP03_I06.addItem(spacerItem9, 2, 0, 1, 1)
        spacerItem10 = QtWidgets.QSpacerItem(1, 1, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_ECP03_I06.addItem(spacerItem10, 0, 0, 1, 1)
        self.ECP_Input16 = QtWidgets.QDoubleSpinBox(self.ECP_frame_InputSet)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ECP_Input16.sizePolicy().hasHeightForWidth())
        self.ECP_Input16.setSizePolicy(sizePolicy)
        self.ECP_Input16.setMinimumSize(QtCore.QSize(120, 0))
        self.ECP_Input16.setMaximumSize(QtCore.QSize(120, 16777215))
        self.ECP_Input16.setSizeIncrement(QtCore.QSize(0, 0))
        self.ECP_Input16.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        self.ECP_Input16.setFont(font)
        self.ECP_Input16.setStyleSheet("padding: 3px;")
        self.ECP_Input16.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.ECP_Input16.setProperty("showGroupSeparator", True)
        self.ECP_Input16.setMaximum(1000.0)
        self.ECP_Input16.setStepType(QtWidgets.QAbstractSpinBox.DefaultStepType)
        self.ECP_Input16.setProperty("value", 381.0)
        self.ECP_Input16.setObjectName("ECP_Input16")
        self.gridLayout_ECP03_I06.addWidget(self.ECP_Input16, 1, 0, 1, 1)
        self.gridLayout_ECP_I01.addLayout(self.gridLayout_ECP03_I06, 10, 3, 1, 1)
        self.gridLayout_ECP02_I03 = QtWidgets.QGridLayout()
        self.gridLayout_ECP02_I03.setSpacing(0)
        self.gridLayout_ECP02_I03.setObjectName("gridLayout_ECP02_I03")
        spacerItem11 = QtWidgets.QSpacerItem(1, 1, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_ECP02_I03.addItem(spacerItem11, 2, 0, 1, 1)
        spacerItem12 = QtWidgets.QSpacerItem(1, 1, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_ECP02_I03.addItem(spacerItem12, 0, 0, 1, 1)
        self.ECP_Input03 = QtWidgets.QDoubleSpinBox(self.ECP_frame_InputSet)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ECP_Input03.sizePolicy().hasHeightForWidth())
        self.ECP_Input03.setSizePolicy(sizePolicy)
        self.ECP_Input03.setMinimumSize(QtCore.QSize(120, 0))
        self.ECP_Input03.setMaximumSize(QtCore.QSize(120, 16777215))
        self.ECP_Input03.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        self.ECP_Input03.setFont(font)
        self.ECP_Input03.setStyleSheet("padding: 3px;")
        self.ECP_Input03.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.ECP_Input03.setSuffix("")
        self.ECP_Input03.setMaximum(1000.0)
        self.ECP_Input03.setProperty("value", 100.0)
        self.ECP_Input03.setObjectName("ECP_Input03")
        self.gridLayout_ECP02_I03.addWidget(self.ECP_Input03, 1, 0, 1, 1)
        self.gridLayout_ECP_I01.addLayout(self.gridLayout_ECP02_I03, 5, 3, 1, 1)
        self.gridLayout_ECP02_I04 = QtWidgets.QGridLayout()
        self.gridLayout_ECP02_I04.setSpacing(0)
        self.gridLayout_ECP02_I04.setObjectName("gridLayout_ECP02_I04")
        spacerItem13 = QtWidgets.QSpacerItem(1, 1, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_ECP02_I04.addItem(spacerItem13, 0, 0, 1, 1)
        spacerItem14 = QtWidgets.QSpacerItem(1, 1, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_ECP02_I04.addItem(spacerItem14, 2, 0, 1, 1)
        self.ECP_Input04 = QtWidgets.QDoubleSpinBox(self.ECP_frame_InputSet)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ECP_Input04.sizePolicy().hasHeightForWidth())
        self.ECP_Input04.setSizePolicy(sizePolicy)
        self.ECP_Input04.setMinimumSize(QtCore.QSize(120, 0))
        self.ECP_Input04.setMaximumSize(QtCore.QSize(120, 16777215))
        self.ECP_Input04.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        self.ECP_Input04.setFont(font)
        self.ECP_Input04.setStyleSheet("padding: 3px;")
        self.ECP_Input04.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.ECP_Input04.setProperty("showGroupSeparator", True)
        self.ECP_Input04.setMaximum(100000.0)
        self.ECP_Input04.setStepType(QtWidgets.QAbstractSpinBox.DefaultStepType)
        self.ECP_Input04.setProperty("value", 0.0)
        self.ECP_Input04.setObjectName("ECP_Input04")
        self.gridLayout_ECP02_I04.addWidget(self.ECP_Input04, 1, 0, 1, 1)
        self.gridLayout_ECP_I01.addLayout(self.gridLayout_ECP02_I04, 4, 3, 1, 1)
        self.gridLayout_ECP03_I04 = QtWidgets.QGridLayout()
        self.gridLayout_ECP03_I04.setSpacing(0)
        self.gridLayout_ECP03_I04.setObjectName("gridLayout_ECP03_I04")
        spacerItem15 = QtWidgets.QSpacerItem(1, 1, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_ECP03_I04.addItem(spacerItem15, 2, 0, 1, 1)
        spacerItem16 = QtWidgets.QSpacerItem(1, 1, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_ECP03_I04.addItem(spacerItem16, 0, 0, 1, 1)
        self.ECP_Input14 = QtWidgets.QDoubleSpinBox(self.ECP_frame_InputSet)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ECP_Input14.sizePolicy().hasHeightForWidth())
        self.ECP_Input14.setSizePolicy(sizePolicy)
        self.ECP_Input14.setMinimumSize(QtCore.QSize(120, 0))
        self.ECP_Input14.setMaximumSize(QtCore.QSize(120, 16777215))
        self.ECP_Input14.setSizeIncrement(QtCore.QSize(0, 0))
        self.ECP_Input14.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        self.ECP_Input14.setFont(font)
        self.ECP_Input14.setStyleSheet("padding: 3px;")
        self.ECP_Input14.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.ECP_Input14.setProperty("showGroupSeparator", True)
        self.ECP_Input14.setMaximum(1000.0)
        self.ECP_Input14.setStepType(QtWidgets.QAbstractSpinBox.DefaultStepType)
        self.ECP_Input14.setProperty("value", 381.0)
        self.ECP_Input14.setObjectName("ECP_Input14")
        self.gridLayout_ECP03_I04.addWidget(self.ECP_Input14, 1, 0, 1, 1)
        self.gridLayout_ECP_I01.addLayout(self.gridLayout_ECP03_I04, 8, 3, 1, 1)
        self.gridLayout_ECP_InputSetup01 = QtWidgets.QGridLayout()
        self.gridLayout_ECP_InputSetup01.setSpacing(0)
        self.gridLayout_ECP_InputSetup01.setObjectName("gridLayout_ECP_InputSetup01")
        spacerItem17 = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.gridLayout_ECP_InputSetup01.addItem(spacerItem17, 0, 0, 1, 1)
        spacerItem18 = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.gridLayout_ECP_InputSetup01.addItem(spacerItem18, 2, 0, 1, 1)
        self.ECP_InputSelect = QtWidgets.QComboBox(self.ECP_frame_InputSet)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ECP_InputSelect.sizePolicy().hasHeightForWidth())
        self.ECP_InputSelect.setSizePolicy(sizePolicy)
        self.ECP_InputSelect.setMinimumSize(QtCore.QSize(120, 0))
        self.ECP_InputSelect.setMaximumSize(QtCore.QSize(120, 16777215))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.ECP_InputSelect.setFont(font)
        self.ECP_InputSelect.setObjectName("ECP_InputSelect")
        self.ECP_InputSelect.addItem("")
        self.ECP_InputSelect.addItem("")
        self.gridLayout_ECP_InputSetup01.addWidget(self.ECP_InputSelect, 1, 0, 1, 1)
        self.gridLayout_ECP_I01.addLayout(self.gridLayout_ECP_InputSetup01, 1, 3, 1, 1)
        self.LabelSub_ECP13 = QtWidgets.QLabel(self.ECP_frame_InputSet)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LabelSub_ECP13.sizePolicy().hasHeightForWidth())
        self.LabelSub_ECP13.setSizePolicy(sizePolicy)
        self.LabelSub_ECP13.setMinimumSize(QtCore.QSize(120, 0))
        self.LabelSub_ECP13.setMaximumSize(QtCore.QSize(120, 16777215))
        self.LabelSub_ECP13.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.LabelSub_ECP13.setFont(font)
        self.LabelSub_ECP13.setObjectName("LabelSub_ECP13")
        self.gridLayout_ECP_I01.addWidget(self.LabelSub_ECP13, 7, 1, 1, 1)
        self.LabelSub_ECP11 = QtWidgets.QLabel(self.ECP_frame_InputSet)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LabelSub_ECP11.sizePolicy().hasHeightForWidth())
        self.LabelSub_ECP11.setSizePolicy(sizePolicy)
        self.LabelSub_ECP11.setMinimumSize(QtCore.QSize(120, 0))
        self.LabelSub_ECP11.setMaximumSize(QtCore.QSize(120, 16777215))
        self.LabelSub_ECP11.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.LabelSub_ECP11.setFont(font)
        self.LabelSub_ECP11.setObjectName("LabelSub_ECP11")
        self.gridLayout_ECP_I01.addWidget(self.LabelSub_ECP11, 6, 1, 1, 1)
        self.LabelSub_ECP16 = QtWidgets.QLabel(self.ECP_frame_InputSet)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LabelSub_ECP16.sizePolicy().hasHeightForWidth())
        self.LabelSub_ECP16.setSizePolicy(sizePolicy)
        self.LabelSub_ECP16.setMinimumSize(QtCore.QSize(120, 0))
        self.LabelSub_ECP16.setMaximumSize(QtCore.QSize(120, 16777215))
        self.LabelSub_ECP16.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.LabelSub_ECP16.setFont(font)
        self.LabelSub_ECP16.setObjectName("LabelSub_ECP16")
        self.gridLayout_ECP_I01.addWidget(self.LabelSub_ECP16, 10, 1, 1, 1)
        self.LabelSub_ECP14 = QtWidgets.QLabel(self.ECP_frame_InputSet)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LabelSub_ECP14.sizePolicy().hasHeightForWidth())
        self.LabelSub_ECP14.setSizePolicy(sizePolicy)
        self.LabelSub_ECP14.setMinimumSize(QtCore.QSize(120, 0))
        self.LabelSub_ECP14.setMaximumSize(QtCore.QSize(120, 16777215))
        self.LabelSub_ECP14.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.LabelSub_ECP14.setFont(font)
        self.LabelSub_ECP14.setObjectName("LabelSub_ECP14")
        self.gridLayout_ECP_I01.addWidget(self.LabelSub_ECP14, 8, 1, 1, 1)
        self.LabelSub_Selete01 = QtWidgets.QLabel(self.ECP_frame_InputSet)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LabelSub_Selete01.sizePolicy().hasHeightForWidth())
        self.LabelSub_Selete01.setSizePolicy(sizePolicy)
        self.LabelSub_Selete01.setMinimumSize(QtCore.QSize(120, 0))
        self.LabelSub_Selete01.setMaximumSize(QtCore.QSize(120, 16777215))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.LabelSub_Selete01.setFont(font)
        self.LabelSub_Selete01.setObjectName("LabelSub_Selete01")
        self.gridLayout_ECP_I01.addWidget(self.LabelSub_Selete01, 2, 1, 1, 1)
        self.LabelSub_ECP04 = QtWidgets.QLabel(self.ECP_frame_InputSet)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LabelSub_ECP04.sizePolicy().hasHeightForWidth())
        self.LabelSub_ECP04.setSizePolicy(sizePolicy)
        self.LabelSub_ECP04.setMinimumSize(QtCore.QSize(120, 0))
        self.LabelSub_ECP04.setMaximumSize(QtCore.QSize(120, 16777215))
        self.LabelSub_ECP04.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.LabelSub_ECP04.setFont(font)
        self.LabelSub_ECP04.setObjectName("LabelSub_ECP04")
        self.gridLayout_ECP_I01.addWidget(self.LabelSub_ECP04, 4, 1, 1, 1)
        self.gridLayout_InputModel = QtWidgets.QGridLayout()
        self.gridLayout_InputModel.setSpacing(0)
        self.gridLayout_InputModel.setObjectName("gridLayout_InputModel")
        self.pushButton_InputModel = QtWidgets.QPushButton(self.ECP_frame_InputSet)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.pushButton_InputModel.sizePolicy().hasHeightForWidth())
        self.pushButton_InputModel.setSizePolicy(sizePolicy)
        self.pushButton_InputModel.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.pushButton_InputModel.setFont(font)
        self.pushButton_InputModel.setStyleSheet("QPushButton {\n"
"    border: 2px solid rgb(52, 59, 72);\n"
"    border-radius: 5px;\n"
"    background-color: rgb(52, 59, 72);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(57, 65, 79);\n"
"    border: 2px solid rgb(61, 70, 86);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgb(67, 77, 93);\n"
"    border: 2px solid rgb(43, 50, 61);\n"
"}")
        self.pushButton_InputModel.setObjectName("pushButton_InputModel")
        self.gridLayout_InputModel.addWidget(self.pushButton_InputModel, 1, 0, 1, 1)
        spacerItem19 = QtWidgets.QSpacerItem(0, 4, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_InputModel.addItem(spacerItem19, 0, 0, 1, 1)
        spacerItem20 = QtWidgets.QSpacerItem(0, 1, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_InputModel.addItem(spacerItem20, 2, 0, 1, 1)
        self.gridLayout_ECP_I01.addLayout(self.gridLayout_InputModel, 2, 3, 1, 1)
        self.gridLayout_ECPTotal.addLayout(self.gridLayout_ECP_I01, 0, 0, 1, 1)
        self.ECP_Main08_CalcButton = QtWidgets.QFrame(self.ECP_frame_InputSet)
        self.ECP_Main08_CalcButton.setMinimumSize(QtCore.QSize(0, 0))
        self.ECP_Main08_CalcButton.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.ECP_Main08_CalcButton.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ECP_Main08_CalcButton.setObjectName("ECP_Main08_CalcButton")
        self.ECP_CalcButton_Grid = QtWidgets.QGridLayout(self.ECP_Main08_CalcButton)
        self.ECP_CalcButton_Grid.setContentsMargins(0, 0, 0, 0)
        self.ECP_CalcButton_Grid.setSpacing(6)
        self.ECP_CalcButton_Grid.setObjectName("ECP_CalcButton_Grid")
        self.ECP_IO_button = QtWidgets.QPushButton(self.ECP_Main08_CalcButton)
        self.ECP_IO_button.setMinimumSize(QtCore.QSize(80, 50))
        self.ECP_IO_button.setMaximumSize(QtCore.QSize(80, 16777215))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.ECP_IO_button.setFont(font)
        self.ECP_IO_button.setStyleSheet("QPushButton {\n"
"    border: 2px solid rgb(52, 59, 72);\n"
"    border-radius: 5px;\n"
"    background-color: rgb(52, 59, 72);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(57, 65, 79);\n"
"    border: 2px solid rgb(61, 70, 86);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgb(67, 77, 93);\n"
"    border: 2px solid rgb(43, 50, 61);\n"
"}")
        self.ECP_IO_button.setObjectName("ECP_IO_button")
        self.ECP_CalcButton_Grid.addWidget(self.ECP_IO_button, 1, 1, 1, 1)
        self.ECP_run_button = QtWidgets.QPushButton(self.ECP_Main08_CalcButton)
        self.ECP_run_button.setMinimumSize(QtCore.QSize(100, 50))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.ECP_run_button.setFont(font)
        self.ECP_run_button.setStyleSheet("QPushButton {\n"
"    border: 2px solid rgb(52, 59, 72);\n"
"    border-radius: 5px;\n"
"    background-color: rgb(85, 170, 255);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(72, 144, 216);\n"
"    border: 2px solid rgb(61, 70, 86);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgb(52, 59, 72);\n"
"    border: 2px solid rgb(43, 50, 61);\n"
"}")
        self.ECP_run_button.setObjectName("ECP_run_button")
        self.ECP_CalcButton_Grid.addWidget(self.ECP_run_button, 1, 2, 1, 1)
        self.ECP_save_button = QtWidgets.QPushButton(self.ECP_Main08_CalcButton)
        self.ECP_save_button.setMinimumSize(QtCore.QSize(80, 50))
        self.ECP_save_button.setMaximumSize(QtCore.QSize(80, 16777215))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.ECP_save_button.setFont(font)
        self.ECP_save_button.setStyleSheet("QPushButton {\n"
"    border: 2px solid rgb(52, 59, 72);\n"
"    border-radius: 5px;\n"
"    background-color: rgb(52, 59, 72);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(57, 65, 79);\n"
"    border: 2px solid rgb(61, 70, 86);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgb(67, 77, 93);\n"
"    border: 2px solid rgb(43, 50, 61);\n"
"}")
        self.ECP_save_button.setObjectName("ECP_save_button")
        self.ECP_CalcButton_Grid.addWidget(self.ECP_save_button, 1, 0, 1, 1)
        self.gridLayout_ECPTotal.addWidget(self.ECP_Main08_CalcButton, 3, 0, 1, 1)
        spacerItem21 = QtWidgets.QSpacerItem(273, 10000, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_ECPTotal.addItem(spacerItem21, 1, 0, 2, 1)
        self.gridLayout_ECP_DUMMY.addLayout(self.gridLayout_ECPTotal, 0, 1, 1, 1)
        self.gridLayout_52.addWidget(self.ECP_frame_InputSet, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.ECP_frame_MainWindow, 0, 0, 1, 1)

        self.retranslateUi(unitWidget_ECP)
        QtCore.QMetaObject.connectSlotsByName(unitWidget_ECP)
        unitWidget_ECP.setTabOrder(self.ECP_InputSelect, self.pushButton_InputModel)
        unitWidget_ECP.setTabOrder(self.pushButton_InputModel, self.ECP_Input00)
        unitWidget_ECP.setTabOrder(self.ECP_Input00, self.ECP_Input04)
        unitWidget_ECP.setTabOrder(self.ECP_Input04, self.ECP_Input03)
        unitWidget_ECP.setTabOrder(self.ECP_Input03, self.ECP_Input12)
        unitWidget_ECP.setTabOrder(self.ECP_Input12, self.ECP_Input13)
        unitWidget_ECP.setTabOrder(self.ECP_Input13, self.ECP_Input14)
        unitWidget_ECP.setTabOrder(self.ECP_Input14, self.ECP_Input15)
        unitWidget_ECP.setTabOrder(self.ECP_Input15, self.ECP_Input16)
        unitWidget_ECP.setTabOrder(self.ECP_Input16, self.ECP_IO_button)
        unitWidget_ECP.setTabOrder(self.ECP_IO_button, self.ECP_run_button)

    def retranslateUi(self, unitWidget_ECP):
        _translate = QtCore.QCoreApplication.translate
        unitWidget_ECP.setWindowTitle(_translate("unitWidget_ECP", "Form"))
        # self.labelY_12Y.setText(_translate("unitWidget_ECP", "12"))
        # self.labelY_11Y.setText(_translate("unitWidget_ECP", "11"))
        # self.labelX_J.setText(_translate("unitWidget_ECP", "J"))
        # self.labelX_L.setText(_translate("unitWidget_ECP", "L"))
        # self.labelY_09Y.setText(_translate("unitWidget_ECP", "9"))
        # self.labelY_08Y.setText(_translate("unitWidget_ECP", "8"))
        # self.labelX_R.setText(_translate("unitWidget_ECP", "R"))
        # self.labelY_15Y.setText(_translate("unitWidget_ECP", "15"))
        # self.labelX_M.setText(_translate("unitWidget_ECP", "M"))
        # self.labelX_H.setText(_translate("unitWidget_ECP", "H"))
        # self.labelX_P.setText(_translate("unitWidget_ECP", "P"))
        # self.labelX_K.setText(_translate("unitWidget_ECP", "K"))
        # self.labelY_14Y.setText(_translate("unitWidget_ECP", "14"))
        # self.labelY_10Y.setText(_translate("unitWidget_ECP", "10"))
        # self.labelY_13Y.setText(_translate("unitWidget_ECP", "13"))
        # self.labelX_N.setText(_translate("unitWidget_ECP", "N"))
        self.LabelSub_Selete00.setText(_translate("unitWidget_ECP", "<html><head/><body><p>Input Type</p></body></html>"))
        self.LabelSub_ECP00.setText(_translate("unitWidget_ECP", "<html><head/><body><p>Calc. Target</p></body></html>"))
        self.LabelSub_ECP03.setText(_translate("unitWidget_ECP", "<html><head/><body><p>Power Before<br/>Shutdown (%)</p></body></html>"))
        self.LabelSub_ECP15.setText(_translate("unitWidget_ECP", "<html><head/><body><p>Bank 5 (cm)</p></body></html>"))
        self.ECP_Input00.setItemText(0, _translate("unitWidget_ECP", "Boron"))
        self.ECP_Input00.setItemText(1, _translate("unitWidget_ECP", "Rod Pos."))
        self.LabelTitle_ECP01.setText(_translate("unitWidget_ECP", "Input Setup"))
        self.ECP_InputSelect.setItemText(0, _translate("unitWidget_ECP", "NDR"))
        self.ECP_InputSelect.setItemText(1, _translate("unitWidget_ECP", "CECOR"))
        self.LabelSub_ECP13.setText(_translate("unitWidget_ECP", "<html><head/><body><p>CBC (ppm)</span></p></body></html>"))
        self.LabelSub_ECP11.setText(_translate("unitWidget_ECP", "<html><head/><body><p>ΔTime (Hour)</p></body></html>"))
        self.LabelSub_ECP16.setText(_translate("unitWidget_ECP", "<html><head/><body><p>Bank 4 (cm)</p></body></html>"))
        self.LabelSub_ECP14.setText(_translate("unitWidget_ECP", "<html><head/><body><p>Bank P (cm)</p></body></html>"))
        self.LabelSub_Selete01.setText(_translate("unitWidget_ECP", "<html><head/><body><p>Model Setup</p></body></html>"))
        self.LabelSub_ECP04.setText(_translate("unitWidget_ECP", "<html><head/><body><p>Cycle Burnup<br/>(MWD/MTU)</p></body></html>"))
        self.pushButton_InputModel.setText(_translate("unitWidget_ECP", "Load Model"))
        self.ECP_IO_button.setText(_translate("unitWidget_ECP", "I/O"))
        self.ECP_run_button.setText(_translate("unitWidget_ECP", "Run"))
        self.ECP_save_button.setText(_translate("unitWidget_ECP", "Save"))
