# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'unitWidget_Lifetime_rev1.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_unitWidget_Lifetime(object):
    def setupUi(self, unitWidget_Lifetime):
        unitWidget_Lifetime.setObjectName("unitWidget_Lifetime")
        unitWidget_Lifetime.resize(1825, 1382)
        self.gridLayout = QtWidgets.QGridLayout(unitWidget_Lifetime)
        self.gridLayout.setObjectName("gridLayout")
        self.Lifetime_frame_MainWindow = QtWidgets.QFrame(unitWidget_Lifetime)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Lifetime_frame_MainWindow.sizePolicy().hasHeightForWidth())
        self.Lifetime_frame_MainWindow.setSizePolicy(sizePolicy)
        self.Lifetime_frame_MainWindow.setStyleSheet("background-color: rgb(44, 49, 60);\n"
"/* LINE EDIT */\n"
"QLineEdit {\n"
"    background-color: rgb(27, 29, 35);\n"
"    border-radius: 5px;\n"
"    border: 2px solid rgb(27, 29, 35);\n"
"    padding-left: 10px;\n"
"}\n"
"QLineEdit:hover {\n"
"    border: 2px solid rgb(64, 71, 88);\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 2px solid rgb(91, 101, 124);\n"
"}\n"
"\n"
"/* SCROLL BARS */\n"
"QScrollBar:horizontal {\n"
"    border: none;\n"
"    background: rgb(52, 59, 72);\n"
"    height: 14px;\n"
"    margin: 0px 21px 0 21px;\n"
"    border-radius: 0px;\n"
"}\n"
"QScrollBar::handle:horizontal {\n"
"    background: rgb(85, 170, 255);\n"
"    min-width: 25px;\n"
"    border-radius: 7px\n"
"}\n"
"QScrollBar::add-line:horizontal {\n"
"    border: none;\n"
"    background: rgb(55, 63, 77);\n"
"    width: 20px;\n"
"    border-top-right-radius: 7px;\n"
"    border-bottom-right-radius: 7px;\n"
"    subcontrol-position: right;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::sub-line:horizontal {\n"
"    border: none;\n"
"    background: rgb(55, 63, 77);\n"
"    width: 20px;\n"
"    border-top-left-radius: 7px;\n"
"    border-bottom-left-radius: 7px;\n"
"    subcontrol-position: left;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::up-arrow:horizontal, QScrollBar::down-arrow:horizontal\n"
"{\n"
"     background: none;\n"
"}\n"
"QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal\n"
"{\n"
"     background: none;\n"
"}\n"
" QScrollBar:vertical {\n"
"    border: none;\n"
"    background: rgb(52, 59, 72);\n"
"    width: 14px;\n"
"    margin: 21px 0 21px 0;\n"
"    border-radius: 0px;\n"
" }\n"
" QScrollBar::handle:vertical {    \n"
"    background: rgb(85, 170, 255);\n"
"    min-height: 25px;\n"
"    border-radius: 7px\n"
" }\n"
" QScrollBar::add-line:vertical {\n"
"     border: none;\n"
"    background: rgb(55, 63, 77);\n"
"     height: 20px;\n"
"    border-bottom-left-radius: 7px;\n"
"    border-bottom-right-radius: 7px;\n"
"     subcontrol-position: bottom;\n"
"     subcontrol-origin: margin;\n"
" }\n"
" QScrollBar::sub-line:vertical {\n"
"    border: none;\n"
"    background: rgb(55, 63, 77);\n"
"     height: 20px;\n"
"    border-top-left-radius: 7px;\n"
"    border-top-right-radius: 7px;\n"
"     subcontrol-position: top;\n"
"     subcontrol-origin: margin;\n"
" }\n"
" QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical {\n"
"     background: none;\n"
" }\n"
"\n"
" QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"     background: none;\n"
" }\n"
"\n"
"/* CHECKBOX */\n"
"QCheckBox::indicator {\n"
"    border: 3px solid rgb(52, 59, 72);\n"
"    width: 15px;\n"
"    height: 15px;\n"
"    border-radius: 10px;\n"
"    background: rgb(44, 49, 60);\n"
"}\n"
"QCheckBox::indicator:hover {\n"
"    border: 3px solid rgb(58, 66, 81);\n"
"}\n"
"QCheckBox::indicator:checked {\n"
"    background: 3px solid rgb(52, 59, 72);\n"
"    border: 3px solid rgb(52, 59, 72);    \n"
"    background-image: url(:/16x16/icons/16x16/cil-check-alt.png);\n"
"}\n"
"\n"
"/* RADIO BUTTON */\n"
"QRadioButton::indicator {\n"
"    border: 3px solid rgb(52, 59, 72);\n"
"    width: 15px;\n"
"    height: 15px;\n"
"    border-radius: 10px;\n"
"    background: rgb(44, 49, 60);\n"
"}\n"
"QRadioButton::indicator:hover {\n"
"    border: 3px solid rgb(58, 66, 81);\n"
"}\n"
"QRadioButton::indicator:checked {\n"
"    background: 3px solid rgb(94, 106, 130);\n"
"    border: 3px solid rgb(52, 59, 72);    \n"
"}\n"
"\n"
"/* COMBOBOX */\n"
"QComboBox{\n"
"    background-color: rgb(27, 29, 35);\n"
"    border-radius: 5px;\n"
"    border: 2px solid rgb(27, 29, 35);\n"
"    padding: 5px;\n"
"    padding-left: 10px;\n"
"}\n"
"QComboBox:hover{\n"
"    border: 2px solid rgb(64, 71, 88);\n"
"}\n"
"QComboBox::drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    width: 25px; \n"
"    border-left-width: 3px;\n"
"    border-left-color: rgba(39, 44, 54, 150);\n"
"    border-left-style: solid;\n"
"    border-top-right-radius: 3px;\n"
"    border-bottom-right-radius: 3px;    \n"
"    background-image: url(:/16x16/icons/16x16/cil-arrow-bottom.png);\n"
"    background-position: center;\n"
"    background-repeat: no-reperat;\n"
" }\n"
"QComboBox QAbstractItemView {\n"
"    color: rgb(85, 170, 255);    \n"
"    background-color: rgb(27, 29, 35);\n"
"    padding: 10px;\n"
"    selection-background-color: rgb(39, 44, 54);\n"
"}\n"
"\n"
"/* SLIDERS */\n"
"QSlider::groove:horizontal {\n"
"    border-radius: 9px;\n"
"    height: 18px;\n"
"    margin: 0px;\n"
"    background-color: rgb(52, 59, 72);\n"
"}\n"
"QSlider::groove:horizontal:hover {\n"
"    background-color: rgb(55, 62, 76);\n"
"}\n"
"QSlider::handle:horizontal {\n"
"    background-color: rgb(85, 170, 255);\n"
"    border: none;\n"
"    height: 18px;\n"
"    width: 18px;\n"
"    margin: 0px;\n"
"    border-radius: 9px;\n"
"}\n"
"QSlider::handle:horizontal:hover {\n"
"    background-color: rgb(105, 180, 255);\n"
"}\n"
"QSlider::handle:horizontal:pressed {\n"
"    background-color: rgb(65, 130, 195);\n"
"}\n"
"\n"
"QSlider::groove:vertical {\n"
"    border-radius: 9px;\n"
"    width: 18px;\n"
"    margin: 0px;\n"
"    background-color: rgb(52, 59, 72);\n"
"}\n"
"QSlider::groove:vertical:hover {\n"
"    background-color: rgb(55, 62, 76);\n"
"}\n"
"QSlider::handle:vertical {\n"
"    background-color: rgb(85, 170, 255);\n"
"    border: none;\n"
"    height: 18px;\n"
"    width: 18px;\n"
"    margin: 0px;\n"
"    border-radius: 9px;\n"
"}\n"
"QSlider::handle:vertical:hover {\n"
"    background-color: rgb(105, 180, 255);\n"
"}\n"
"QSlider::handle:vertical:pressed {\n"
"    background-color: rgb(65, 130, 195);\n"
"}\n"
"/* QTableWidget*/\n"
"QTableWidget {    \n"
"    background-color: rgb(38, 44, 53);\n"
"    padding: 10px;\n"
"    border-radius: 15px;\n"
"    gridline-color: rgb(44, 49, 60);\n"
"    border-bottom: 1px solid rgb(44, 49, 60);\n"
"}\n"
"QTableWidget::item{\n"
"    border-color: rgb(44, 49, 60);\n"
"    padding-left: 5px;\n"
"    padding-right: 5px;\n"
"    gridline-color: rgb(44, 49, 60);\n"
"}\n"
"QTableWidget::item:selected{\n"
"    background-color: rgb(85, 170, 255);\n"
"}\n"
"QScrollBar:horizontal {\n"
"    border: none;\n"
"    background: rgb(52, 59, 72);\n"
"    height: 14px;\n"
"    margin: 0px 21px 0 21px;\n"
"    border-radius: 0px;\n"
"}\n"
"\n"
"QScrollBar:handle:horizontal {\n"
"    background: rgb(91, 101, 124);\n"
"\n"
"}\n"
"\n"
" QScrollBar:vertical {\n"
"    border: none;\n"
"    background: rgb(52, 59, 72);\n"
"    width: 14px;\n"
"    margin: 21px 0 21px 0;\n"
"    border-radius: 0px;\n"
" }\n"
"QHeaderView::section{\n"
"    Background-color: rgb(39, 44, 54);\n"
"    max-width: 30px;\n"
"    border: 1px solid rgb(44, 49, 60);\n"
"    border-style: none;\n"
"    border-bottom: 1px solid rgb(44, 49, 60);\n"
"    border-right: 1px solid rgb(44, 49, 60);\n"
"}\n"
"QTableWidget::horizontalHeader {    \n"
"    background-color: rgb(190, 190, 190);\n"
"}\n"
"\n"
"QHeaderView::section:horizontal\n"
"{\n"
"    background-color: rgb(51, 59, 70);\n"
"    padding: 3px;\n"
"    border-top-left-radius: 7px;\n"
"    border-top-right-radius: 7px;\n"
"    color: rgb(167,    174, 183);\n"
"}\n"
"QHeaderView::section:vertical\n"
"{\n"
"    border: 1px solid rgb(44, 49, 60);\n"
"}\n"
"\n"
"QScrollBar:handle:vertical {\n"
"    background: rgb(91, 101, 124);\n"
"\n"
"}\n"
"\n"
"QTableCornerButton::section{ \n"
"\n"
"    background-color: rgb(38, 44, 53);\n"
"}\n"
"\n"
"")
        self.Lifetime_frame_MainWindow.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.Lifetime_frame_MainWindow.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Lifetime_frame_MainWindow.setObjectName("Lifetime_frame_MainWindow")
        self.gridLayout_Lifetime_frame_MainWindow = QtWidgets.QGridLayout(self.Lifetime_frame_MainWindow)
        self.gridLayout_Lifetime_frame_MainWindow.setSpacing(3)
        self.gridLayout_Lifetime_frame_MainWindow.setObjectName("gridLayout_Lifetime_frame_MainWindow")
        self.frame_lIfetime_tabRodPos = QtWidgets.QFrame(self.Lifetime_frame_MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(200)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_lIfetime_tabRodPos.sizePolicy().hasHeightForWidth())
        self.frame_lIfetime_tabRodPos.setSizePolicy(sizePolicy)
        self.frame_lIfetime_tabRodPos.setAutoFillBackground(False)
        self.frame_lIfetime_tabRodPos.setStyleSheet("background-color: rgb(51, 58, 72); \n"
"border-radius: 10px;")
        self.frame_lIfetime_tabRodPos.setObjectName("frame_lIfetime_tabRodPos")
        self.gridLayout_167 = QtWidgets.QGridLayout(self.frame_lIfetime_tabRodPos)
        self.gridLayout_167.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_167.setSpacing(6)
        self.gridLayout_167.setObjectName("gridLayout_167")
        self.Lifetime_WidgetAxial = QtWidgets.QWidget(self.frame_lIfetime_tabRodPos)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(6)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.Lifetime_WidgetAxial.sizePolicy().hasHeightForWidth())
        self.Lifetime_WidgetAxial.setSizePolicy(sizePolicy)
        self.Lifetime_WidgetAxial.setMinimumSize(QtCore.QSize(0, 0))
        self.Lifetime_WidgetAxial.setObjectName("Lifetime_WidgetAxial")
        self.gridLayout_167.addWidget(self.Lifetime_WidgetAxial, 0, 1, 1, 1)
        self.Lifetime_WidgetRadial = QtWidgets.QWidget(self.frame_lIfetime_tabRodPos)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(6)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.Lifetime_WidgetRadial.sizePolicy().hasHeightForWidth())
        self.Lifetime_WidgetRadial.setSizePolicy(sizePolicy)
        self.Lifetime_WidgetRadial.setMinimumSize(QtCore.QSize(0, 0))
        self.Lifetime_WidgetRadial.setObjectName("Lifetime_WidgetRadial")
        self.gridLayout_167.addWidget(self.Lifetime_WidgetRadial, 1, 1, 1, 1)
        self.Lifetime_widgetChart = QtWidgets.QWidget(self.frame_lIfetime_tabRodPos)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(10)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.Lifetime_widgetChart.sizePolicy().hasHeightForWidth())
        self.Lifetime_widgetChart.setSizePolicy(sizePolicy)
        self.Lifetime_widgetChart.setMinimumSize(QtCore.QSize(0, 0))
        self.Lifetime_widgetChart.setObjectName("Lifetime_widgetChart")
        self.gridLayout_167.addWidget(self.Lifetime_widgetChart, 1, 0, 1, 1)
        self.frame_Lifetime_TableWidget = QtWidgets.QFrame(self.frame_lIfetime_tabRodPos)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_Lifetime_TableWidget.sizePolicy().hasHeightForWidth())
        self.frame_Lifetime_TableWidget.setSizePolicy(sizePolicy)
        self.frame_Lifetime_TableWidget.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_Lifetime_TableWidget.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_Lifetime_TableWidget.setObjectName("frame_Lifetime_TableWidget")
        self.gridlayout_Lifetime_TableWidget = QtWidgets.QGridLayout(self.frame_Lifetime_TableWidget)
        self.gridlayout_Lifetime_TableWidget.setObjectName("gridlayout_Lifetime_TableWidget")
        self.gridLayout_167.addWidget(self.frame_Lifetime_TableWidget, 0, 0, 1, 1)
        self.gridLayout_Lifetime_frame_MainWindow.addWidget(self.frame_lIfetime_tabRodPos, 0, 1, 1, 1)
        self.Lifetime_InputSet_Total = QtWidgets.QFrame(self.Lifetime_frame_MainWindow)
        self.Lifetime_InputSet_Total.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Lifetime_InputSet_Total.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Lifetime_InputSet_Total.setObjectName("Lifetime_InputSet_Total")
        self.gridLayout_Lifetime_InputSet_Total = QtWidgets.QGridLayout(self.Lifetime_InputSet_Total)
        self.gridLayout_Lifetime_InputSet_Total.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_Lifetime_InputSet_Total.setSpacing(0)
        self.gridLayout_Lifetime_InputSet_Total.setObjectName("gridLayout_Lifetime_InputSet_Total")
        self.gridLayout_Lifetime_Total = QtWidgets.QGridLayout()
        self.gridLayout_Lifetime_Total.setObjectName("gridLayout_Lifetime_Total")
        self.LF_Main02 = QtWidgets.QFrame(self.Lifetime_InputSet_Total)
        self.LF_Main02.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.LF_Main02.setFrameShadow(QtWidgets.QFrame.Raised)
        self.LF_Main02.setObjectName("LF_Main02")
        self.gridLayout_Lifetime_Main04_Input = QtWidgets.QGridLayout(self.LF_Main02)
        self.gridLayout_Lifetime_Main04_Input.setContentsMargins(9, 9, 9, 9)
        self.gridLayout_Lifetime_Main04_Input.setSpacing(6)
        self.gridLayout_Lifetime_Main04_Input.setObjectName("gridLayout_Lifetime_Main04_Input")
        self.LF_Main02Grid = QtWidgets.QGridLayout()
        self.LF_Main02Grid.setObjectName("LF_Main02Grid")
        self.LabelSub_LF07 = QtWidgets.QLabel(self.LF_Main02)
        self.LabelSub_LF07.setMinimumSize(QtCore.QSize(105, 0))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.LabelSub_LF07.setFont(font)
        self.LabelSub_LF07.setObjectName("LabelSub_LF07")
        self.LF_Main02Grid.addWidget(self.LabelSub_LF07, 7, 1, 1, 1)
        self.LabelSub_LF04 = QtWidgets.QLabel(self.LF_Main02)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LabelSub_LF04.sizePolicy().hasHeightForWidth())
        self.LabelSub_LF04.setSizePolicy(sizePolicy)
        self.LabelSub_LF04.setMinimumSize(QtCore.QSize(105, 0))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.LabelSub_LF04.setFont(font)
        self.LabelSub_LF04.setObjectName("LabelSub_LF04")
        self.LF_Main02Grid.addWidget(self.LabelSub_LF04, 4, 1, 1, 1)
        self.LabelSub_LF01 = QtWidgets.QLabel(self.LF_Main02)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LabelSub_LF01.sizePolicy().hasHeightForWidth())
        self.LabelSub_LF01.setSizePolicy(sizePolicy)
        self.LabelSub_LF01.setMinimumSize(QtCore.QSize(105, 0))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        self.LabelSub_LF01.setFont(font)
        self.LabelSub_LF01.setObjectName("LabelSub_LF01")
        self.LF_Main02Grid.addWidget(self.LabelSub_LF01, 1, 1, 1, 1)
        self.LabelSub_LF06 = QtWidgets.QLabel(self.LF_Main02)
        self.LabelSub_LF06.setMinimumSize(QtCore.QSize(105, 0))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.LabelSub_LF06.setFont(font)
        self.LabelSub_LF06.setObjectName("LabelSub_LF06")
        self.LF_Main02Grid.addWidget(self.LabelSub_LF06, 6, 1, 1, 1)
        self.LabelSub_LF05 = QtWidgets.QLabel(self.LF_Main02)
        self.LabelSub_LF05.setMinimumSize(QtCore.QSize(105, 0))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.LabelSub_LF05.setFont(font)
        self.LabelSub_LF05.setObjectName("LabelSub_LF05")
        self.LF_Main02Grid.addWidget(self.LabelSub_LF05, 5, 1, 1, 1)
        self.LabelSub_LF02 = QtWidgets.QLabel(self.LF_Main02)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LabelSub_LF02.sizePolicy().hasHeightForWidth())
        self.LabelSub_LF02.setSizePolicy(sizePolicy)
        self.LabelSub_LF02.setMinimumSize(QtCore.QSize(105, 0))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        self.LabelSub_LF02.setFont(font)
        self.LabelSub_LF02.setObjectName("LabelSub_LF02")
        self.LF_Main02Grid.addWidget(self.LabelSub_LF02, 2, 1, 1, 1)
        self.LabelSub_LF08 = QtWidgets.QLabel(self.LF_Main02)
        self.LabelSub_LF08.setMinimumSize(QtCore.QSize(105, 0))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.LabelSub_LF08.setFont(font)
        self.LabelSub_LF08.setObjectName("LabelSub_LF08")
        self.LF_Main02Grid.addWidget(self.LabelSub_LF08, 8, 1, 1, 1)
        self.LabelSub_LF03 = QtWidgets.QLabel(self.LF_Main02)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LabelSub_LF03.sizePolicy().hasHeightForWidth())
        self.LabelSub_LF03.setSizePolicy(sizePolicy)
        self.LabelSub_LF03.setMinimumSize(QtCore.QSize(105, 0))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.LabelSub_LF03.setFont(font)
        self.LabelSub_LF03.setObjectName("LabelSub_LF03")
        self.LF_Main02Grid.addWidget(self.LabelSub_LF03, 3, 1, 1, 1)
        self.gridLayout_Lifetime_Input03_A_4 = QtWidgets.QGridLayout()
        self.gridLayout_Lifetime_Input03_A_4.setSpacing(0)
        self.gridLayout_Lifetime_Input03_A_4.setObjectName("gridLayout_Lifetime_Input03_A_4")
        spacerItem = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.gridLayout_Lifetime_Input03_A_4.addItem(spacerItem, 2, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.gridLayout_Lifetime_Input03_A_4.addItem(spacerItem1, 0, 0, 1, 1)
        self.LF_Input01 = QtWidgets.QDoubleSpinBox(self.LF_Main02)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LF_Input01.sizePolicy().hasHeightForWidth())
        self.LF_Input01.setSizePolicy(sizePolicy)
        self.LF_Input01.setMinimumSize(QtCore.QSize(0, 0))
        self.LF_Input01.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.LF_Input01.setFont(font)
        self.LF_Input01.setStyleSheet("padding: 3px;")
        self.LF_Input01.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.LF_Input01.setProperty("showGroupSeparator", True)
        self.LF_Input01.setDecimals(2)
        self.LF_Input01.setMinimum(0.0)
        self.LF_Input01.setMaximum(100000.0)
        self.LF_Input01.setSingleStep(100.0)
        self.LF_Input01.setStepType(QtWidgets.QAbstractSpinBox.DefaultStepType)
        self.LF_Input01.setProperty("value", 0.0)
        self.LF_Input01.setObjectName("LF_Input01")
        self.gridLayout_Lifetime_Input03_A_4.addWidget(self.LF_Input01, 1, 0, 1, 1)
        self.LF_Main02Grid.addLayout(self.gridLayout_Lifetime_Input03_A_4, 1, 3, 1, 1)
        self.LabelTitle_LF02 = QtWidgets.QLabel(self.LF_Main02)
        self.LabelTitle_LF02.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.LabelTitle_LF02.setFont(font)
        self.LabelTitle_LF02.setObjectName("LabelTitle_LF02")
        self.LF_Main02Grid.addWidget(self.LabelTitle_LF02, 0, 0, 1, 4)
        self.gridLayout_Lifetime_Input03_A_5 = QtWidgets.QGridLayout()
        self.gridLayout_Lifetime_Input03_A_5.setSpacing(0)
        self.gridLayout_Lifetime_Input03_A_5.setObjectName("gridLayout_Lifetime_Input03_A_5")
        spacerItem2 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.gridLayout_Lifetime_Input03_A_5.addItem(spacerItem2, 2, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.gridLayout_Lifetime_Input03_A_5.addItem(spacerItem3, 0, 0, 1, 1)
        self.LF_Input02 = QtWidgets.QDoubleSpinBox(self.LF_Main02)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LF_Input02.sizePolicy().hasHeightForWidth())
        self.LF_Input02.setSizePolicy(sizePolicy)
        self.LF_Input02.setMinimumSize(QtCore.QSize(0, 0))
        self.LF_Input02.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.LF_Input02.setFont(font)
        self.LF_Input02.setStyleSheet("padding: 3px;")
        self.LF_Input02.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.LF_Input02.setProperty("showGroupSeparator", True)
        self.LF_Input02.setDecimals(2)
        self.LF_Input02.setMinimum(0.0)
        self.LF_Input02.setMaximum(100000.0)
        self.LF_Input02.setSingleStep(100.0)
        self.LF_Input02.setStepType(QtWidgets.QAbstractSpinBox.DefaultStepType)
        self.LF_Input02.setProperty("value", 0.0)
        self.LF_Input02.setObjectName("LF_Input02")
        self.gridLayout_Lifetime_Input03_A_5.addWidget(self.LF_Input02, 1, 0, 1, 1)
        self.LF_Main02Grid.addLayout(self.gridLayout_Lifetime_Input03_A_5, 2, 3, 1, 1)
        self.gridLayout_Lifetime_Input03_A = QtWidgets.QGridLayout()
        self.gridLayout_Lifetime_Input03_A.setSpacing(0)
        self.gridLayout_Lifetime_Input03_A.setObjectName("gridLayout_Lifetime_Input03_A")
        spacerItem4 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.gridLayout_Lifetime_Input03_A.addItem(spacerItem4, 0, 0, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.gridLayout_Lifetime_Input03_A.addItem(spacerItem5, 2, 0, 1, 1)
        self.LF_Input03 = QtWidgets.QDoubleSpinBox(self.LF_Main02)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LF_Input03.sizePolicy().hasHeightForWidth())
        self.LF_Input03.setSizePolicy(sizePolicy)
        self.LF_Input03.setMinimumSize(QtCore.QSize(0, 0))
        self.LF_Input03.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.LF_Input03.setFont(font)
        self.LF_Input03.setStyleSheet("padding: 3px;")
        self.LF_Input03.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.LF_Input03.setProperty("showGroupSeparator", True)
        self.LF_Input03.setDecimals(5)
        self.LF_Input03.setMaximum(10.0)
        self.LF_Input03.setSingleStep(0.01)
        self.LF_Input03.setStepType(QtWidgets.QAbstractSpinBox.DefaultStepType)
        self.LF_Input03.setProperty("value", 1.0)
        self.LF_Input03.setObjectName("LF_Input03")
        self.gridLayout_Lifetime_Input03_A.addWidget(self.LF_Input03, 1, 0, 1, 1)
        self.LF_Main02Grid.addLayout(self.gridLayout_Lifetime_Input03_A, 3, 3, 1, 1)
        self.gridLayout_Lifetime_Input03_A_3 = QtWidgets.QGridLayout()
        self.gridLayout_Lifetime_Input03_A_3.setSpacing(0)
        self.gridLayout_Lifetime_Input03_A_3.setObjectName("gridLayout_Lifetime_Input03_A_3")
        spacerItem6 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.gridLayout_Lifetime_Input03_A_3.addItem(spacerItem6, 0, 0, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.gridLayout_Lifetime_Input03_A_3.addItem(spacerItem7, 2, 0, 1, 1)
        self.LF_Input04 = QtWidgets.QDoubleSpinBox(self.LF_Main02)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LF_Input04.sizePolicy().hasHeightForWidth())
        self.LF_Input04.setSizePolicy(sizePolicy)
        self.LF_Input04.setMinimumSize(QtCore.QSize(0, 0))
        self.LF_Input04.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.LF_Input04.setFont(font)
        self.LF_Input04.setStyleSheet("padding: 3px;")
        self.LF_Input04.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.LF_Input04.setProperty("showGroupSeparator", True)
        self.LF_Input04.setMaximum(100000.0)
        self.LF_Input04.setStepType(QtWidgets.QAbstractSpinBox.DefaultStepType)
        self.LF_Input04.setProperty("value", 0.0)
        self.LF_Input04.setObjectName("LF_Input04")
        self.gridLayout_Lifetime_Input03_A_3.addWidget(self.LF_Input04, 1, 0, 1, 1)
        self.LF_Main02Grid.addLayout(self.gridLayout_Lifetime_Input03_A_3, 4, 3, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(5, 5, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.LF_Main02Grid.addItem(spacerItem8, 1, 0, 8, 1)
        self.gridLayout_Lifetime_Input03_A_6 = QtWidgets.QGridLayout()
        self.gridLayout_Lifetime_Input03_A_6.setSpacing(0)
        self.gridLayout_Lifetime_Input03_A_6.setObjectName("gridLayout_Lifetime_Input03_A_6")
        spacerItem9 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.gridLayout_Lifetime_Input03_A_6.addItem(spacerItem9, 0, 0, 1, 1)
        spacerItem10 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.gridLayout_Lifetime_Input03_A_6.addItem(spacerItem10, 2, 0, 1, 1)
        self.LF_Input05 = QtWidgets.QDoubleSpinBox(self.LF_Main02)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LF_Input05.sizePolicy().hasHeightForWidth())
        self.LF_Input05.setSizePolicy(sizePolicy)
        self.LF_Input05.setMinimumSize(QtCore.QSize(0, 0))
        self.LF_Input05.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.LF_Input05.setFont(font)
        self.LF_Input05.setStyleSheet("padding: 3px;")
        self.LF_Input05.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.LF_Input05.setProperty("showGroupSeparator", True)
        self.LF_Input05.setMaximum(100000.0)
        self.LF_Input05.setStepType(QtWidgets.QAbstractSpinBox.DefaultStepType)
        self.LF_Input05.setProperty("value", 50.0)
        self.LF_Input05.setObjectName("LF_Input05")
        self.gridLayout_Lifetime_Input03_A_6.addWidget(self.LF_Input05, 1, 0, 1, 1)
        self.LF_Main02Grid.addLayout(self.gridLayout_Lifetime_Input03_A_6, 5, 3, 1, 1)
        self.gridLayout_Lifetime_Input03_A_7 = QtWidgets.QGridLayout()
        self.gridLayout_Lifetime_Input03_A_7.setSpacing(0)
        self.gridLayout_Lifetime_Input03_A_7.setObjectName("gridLayout_Lifetime_Input03_A_7")
        spacerItem11 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.gridLayout_Lifetime_Input03_A_7.addItem(spacerItem11, 2, 0, 1, 1)
        spacerItem12 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.gridLayout_Lifetime_Input03_A_7.addItem(spacerItem12, 0, 0, 1, 1)
        self.LF_Input06 = QtWidgets.QDoubleSpinBox(self.LF_Main02)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LF_Input06.sizePolicy().hasHeightForWidth())
        self.LF_Input06.setSizePolicy(sizePolicy)
        self.LF_Input06.setMinimumSize(QtCore.QSize(0, 0))
        self.LF_Input06.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.LF_Input06.setFont(font)
        self.LF_Input06.setStyleSheet("padding: 3px;")
        self.LF_Input06.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.LF_Input06.setProperty("showGroupSeparator", True)
        self.LF_Input06.setMaximum(100000.0)
        self.LF_Input06.setStepType(QtWidgets.QAbstractSpinBox.DefaultStepType)
        self.LF_Input06.setProperty("value", 50.0)
        self.LF_Input06.setObjectName("LF_Input06")
        self.gridLayout_Lifetime_Input03_A_7.addWidget(self.LF_Input06, 1, 0, 1, 1)
        self.LF_Main02Grid.addLayout(self.gridLayout_Lifetime_Input03_A_7, 6, 3, 1, 1)
        self.gridLayout_Lifetime_Input03_A_9 = QtWidgets.QGridLayout()
        self.gridLayout_Lifetime_Input03_A_9.setSpacing(0)
        self.gridLayout_Lifetime_Input03_A_9.setObjectName("gridLayout_Lifetime_Input03_A_9")
        spacerItem13 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.gridLayout_Lifetime_Input03_A_9.addItem(spacerItem13, 0, 0, 1, 1)
        spacerItem14 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.gridLayout_Lifetime_Input03_A_9.addItem(spacerItem14, 2, 0, 1, 1)
        self.LF_Input07 = QtWidgets.QDoubleSpinBox(self.LF_Main02)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LF_Input07.sizePolicy().hasHeightForWidth())
        self.LF_Input07.setSizePolicy(sizePolicy)
        self.LF_Input07.setMinimumSize(QtCore.QSize(0, 0))
        self.LF_Input07.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.LF_Input07.setFont(font)
        self.LF_Input07.setStyleSheet("padding: 3px;")
        self.LF_Input07.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.LF_Input07.setProperty("showGroupSeparator", True)
        self.LF_Input07.setMaximum(100000.0)
        self.LF_Input07.setStepType(QtWidgets.QAbstractSpinBox.DefaultStepType)
        self.LF_Input07.setProperty("value", 50.0)
        self.LF_Input07.setObjectName("LF_Input07")
        self.gridLayout_Lifetime_Input03_A_9.addWidget(self.LF_Input07, 1, 0, 1, 1)
        self.LF_Main02Grid.addLayout(self.gridLayout_Lifetime_Input03_A_9, 7, 3, 1, 1)
        self.gridLayout_Lifetime_Input03_A_8 = QtWidgets.QGridLayout()
        self.gridLayout_Lifetime_Input03_A_8.setSpacing(0)
        self.gridLayout_Lifetime_Input03_A_8.setObjectName("gridLayout_Lifetime_Input03_A_8")
        spacerItem15 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.gridLayout_Lifetime_Input03_A_8.addItem(spacerItem15, 2, 0, 1, 1)
        spacerItem16 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.gridLayout_Lifetime_Input03_A_8.addItem(spacerItem16, 0, 0, 1, 1)
        self.LF_Input08 = QtWidgets.QDoubleSpinBox(self.LF_Main02)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LF_Input08.sizePolicy().hasHeightForWidth())
        self.LF_Input08.setSizePolicy(sizePolicy)
        self.LF_Input08.setMinimumSize(QtCore.QSize(0, 0))
        self.LF_Input08.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.LF_Input08.setFont(font)
        self.LF_Input08.setStyleSheet("padding: 3px;")
        self.LF_Input08.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.LF_Input08.setProperty("showGroupSeparator", True)
        self.LF_Input08.setMaximum(100000.0)
        self.LF_Input08.setStepType(QtWidgets.QAbstractSpinBox.DefaultStepType)
        self.LF_Input08.setProperty("value", 50.0)
        self.LF_Input08.setObjectName("LF_Input08")
        self.gridLayout_Lifetime_Input03_A_8.addWidget(self.LF_Input08, 1, 0, 1, 1)
        self.LF_Main02Grid.addLayout(self.gridLayout_Lifetime_Input03_A_8, 8, 3, 1, 1)
        spacerItem17 = QtWidgets.QSpacerItem(1, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.LF_Main02Grid.addItem(spacerItem17, 1, 2, 8, 1)
        self.gridLayout_Lifetime_Main04_Input.addLayout(self.LF_Main02Grid, 0, 0, 1, 1)
        self.gridLayout_Lifetime_Total.addWidget(self.LF_Main02, 0, 0, 1, 1)
        self.gridLayout_Lifetime_InputSet_Total.addLayout(self.gridLayout_Lifetime_Total, 0, 0, 1, 1)
        spacerItem18 = QtWidgets.QSpacerItem(20, 4000, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_Lifetime_InputSet_Total.addItem(spacerItem18, 1, 0, 1, 1)
        self.LF_Main05 = QtWidgets.QFrame(self.Lifetime_InputSet_Total)
        self.LF_Main05.setMinimumSize(QtCore.QSize(0, 0))
        self.LF_Main05.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.LF_Main05.setFrameShadow(QtWidgets.QFrame.Raised)
        self.LF_Main05.setObjectName("LF_Main05")
        self.Lifetime_CalcButton_Grid = QtWidgets.QGridLayout(self.LF_Main05)
        self.Lifetime_CalcButton_Grid.setContentsMargins(0, 0, 0, 0)
        self.Lifetime_CalcButton_Grid.setObjectName("Lifetime_CalcButton_Grid")
        self.Lifetime_save_button = QtWidgets.QPushButton(self.LF_Main05)
        self.Lifetime_save_button.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.Lifetime_save_button.setFont(font)
        self.Lifetime_save_button.setStyleSheet("QPushButton {\n"
"    border: 2px solid rgb(52, 59, 72);\n"
"    border-radius: 5px;\n"
"    background-color: rgb(52, 59, 72);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(57, 65, 79);\n"
"    border: 2px solid rgb(61, 70, 86);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgb(67, 77, 93);\n"
"    border: 2px solid rgb(43, 50, 61);\n"
"}")
        self.Lifetime_save_button.setObjectName("Lifetime_save_button")
        self.Lifetime_CalcButton_Grid.addWidget(self.Lifetime_save_button, 0, 0, 1, 1)
        self.Lifetime_run_button = QtWidgets.QPushButton(self.LF_Main05)
        self.Lifetime_run_button.setMinimumSize(QtCore.QSize(220, 50))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.Lifetime_run_button.setFont(font)
        self.Lifetime_run_button.setStyleSheet("QPushButton {\n"
"    border: 2px solid rgb(52, 59, 72);\n"
"    border-radius: 5px;\n"
"    background-color: rgb(85, 170, 255);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(72, 144, 216);\n"
"    border: 2px solid rgb(61, 70, 86);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgb(52, 59, 72);\n"
"    border: 2px solid rgb(43, 50, 61);\n"
"}")
        self.Lifetime_run_button.setObjectName("Lifetime_run_button")
        self.Lifetime_CalcButton_Grid.addWidget(self.Lifetime_run_button, 0, 1, 1, 1)
        self.gridLayout_Lifetime_InputSet_Total.addWidget(self.LF_Main05, 2, 0, 1, 1)
        self.gridLayout_Lifetime_frame_MainWindow.addWidget(self.Lifetime_InputSet_Total, 0, 0, 2, 1)
        self.gridLayout.addWidget(self.Lifetime_frame_MainWindow, 0, 1, 1, 1)

        self.retranslateUi(unitWidget_Lifetime)
        QtCore.QMetaObject.connectSlotsByName(unitWidget_Lifetime)

    def retranslateUi(self, unitWidget_Lifetime):
        _translate = QtCore.QCoreApplication.translate
        unitWidget_Lifetime.setWindowTitle(_translate("unitWidget_Lifetime", "Form"))
        self.LabelSub_LF07.setText(_translate("unitWidget_Lifetime", "<html><head/><body><p>Bank 4 Position<br/>(cm withdrawn)</p></body></html>"))
        self.LabelSub_LF04.setText(_translate("unitWidget_Lifetime", "Depletion Interval\n"
"(MWD/MTU)"))
        self.LabelSub_LF01.setText(_translate("unitWidget_Lifetime", "Core Power (%)"))
        self.LabelSub_LF06.setText(_translate("unitWidget_Lifetime", "<html><head/><body><p>Bank 5 Position<br/>(cm withdrawn)</p></body></html>"))
        self.LabelSub_LF05.setText(_translate("unitWidget_Lifetime", "<html><head/><body><p>Bank P Position<br/>(cm withdrawn)</p></body></html>"))
        self.LabelSub_LF02.setText(_translate("unitWidget_Lifetime", "<html><head/><body><p>Cycle Burnup<br>(MWD/MTU)</p></body></html>"))
        self.LabelSub_LF08.setText(_translate("unitWidget_Lifetime", "<html><head/><body><p>Bank 3 Position<br/>(cm withdrawn)</p></body></html>"))
        self.LabelSub_LF03.setText(_translate("unitWidget_Lifetime", "Stopping Criterion\n"
"(keff)"))
        self.LabelTitle_LF02.setText(_translate("unitWidget_Lifetime", "Calculation Option"))
        self.Lifetime_save_button.setText(_translate("unitWidget_Lifetime", "Save"))
        self.Lifetime_run_button.setText(_translate("unitWidget_Lifetime", "Run"))
